C+ NATRIF.FOR
C  WNB 920429
C
C  Revisions:
C     RPN 29/9/88
C     HM 14/Dec/91 Added if_simul and if_chain. Old data 
C     		without them is given if_simul=if_chain=1 in the IF table.
C
	SUBROUTINE NATRIF(FCA,FCAPT,M,II)
C
C  Read RPFITS tape table. Based on RPFITS_READ_TABLE
C
C  Result:
C
C	CALL NATRIF( FCA_J:I, FCAPT_J:IO, M_C32(32):IO, II_J:IO)
C				Read IF table from FCA based on card images in M
C				starting at II currently (-1 indicates only FG 
C				wanted).
C	CALL NATRSU( ...)	Read SU table
C	CALL NATRFG( ...)	Read FG table
C	CALL NATRAN( ...)	Read AN table
C	CALL NATRMT( ...)	Read MT table
C	CALL NATRCU( ...)	Read CU table
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'RPF_DEF'	!RPFITS OUTPUT
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER FCA		!FILE CONTROL AREA
	INTEGER FCAPT		!FILE POINTER
	CHARACTER*80 M(32)	!CARD IMAGES
	INTEGER II		!CURRENT CARD IMAGE (OR -1 FOR FG)
C
C  Entry points:
C
C
C  Function references:
C
	LOGICAL WNFRD		!READ DISK
C
C  Data declarations:
C
	INTEGER IAXIS_OFFSET
	INTEGER ICHR(20,32)	!BUFFER
	INTEGER K,L
C-
C
C NATRIF
C
	N_IF=0
	DO WHILE (.TRUE.)
	  DO J=II+1,32
	    IF (NCARD.LT.0) THEN
	      CARD(-NCARD)=M(J)
	      NCARD=NCARD-1
	    END IF
	    IF (M(J)(1:8).EQ.'ENDTABLE') THEN
	      II=J
	      GOTO 999
	    ELSE IF (M(J)(1:8).EQ.'HEADER') THEN
	    ELSE IF (M(J)(1:8).EQ.'COMMENT') THEN
	    ELSE
	      K=N_IF+1
	      READ(M(J),'(I2,1X,F16.3,1X,I2, 1X, F16.3, 1X, I4,
	1            1X, I2, 1X, 4A2, 1X,I1, 1X,F6.1, 1X, BZ, I2,
	1            1X, I2 )')
	1            IF_NUM(K), IF_FREQ(K), IF_INVERT(K),
	1            IF_BW(K), IF_NFREQ(K), IF_NSTOK(K), 
	1            (IF_CSTOK(L,K),L=1,4), IF_SAMPL(K), 
	1            IF_REF(K), IF_SIMUL(K), IF_CHAIN(K)
	      IF (IF_SIMUL(K).EQ.0) THEN
	        IF_SIMUL(K)=1
	      END IF
	      IF (IF_CHAIN(K).EQ.0) THEN
	        IF_CHAIN(K)=1
	      END IF
	      N_IF=N_IF+1
	    END IF
	  END DO
	  JS=WNFRD(FCA,2560,ICHR,FCAPT)		!READ BLOCK
	  FCAPT=FCAPT+2560			!UPDATE PTR
	  DO I1=1,32				!SET CHAR,
	    CALL WNGMTS(80,ICHR(1,I1),M(I1))
	  END DO
	  II=0
	END DO
 999	CONTINUE
	IF_FOUND=.TRUE.
C
	RETURN
C
C NATRSU
C
	ENTRY NATRSU(FCA,FCAPT,M,II)
C
	N_SU=0
	DO WHILE (.TRUE.)
	  DO J=II+1,32
	    IF (NCARD.LT.0) THEN
	      CARD(-NCARD)=M(J)
	      NCARD=NCARD-1
	    END IF
	    IF (M(J)(1:8).EQ.'ENDTABLE') THEN
	      II=J
	      GOTO 998
	    ELSE IF (M(J)(1:8).EQ.'HEADER') THEN
	    ELSE IF (M(J)(1:8).EQ.'COMMENT') THEN
	    ELSE
	      K=N_SU+1
	      READ(M(J),'(I2,1X,A16,1X,F12.9,1X,F12.9,1X,A4,
	1            1X,F11.9,1X,F11.9)')
	1            SU_NUM(K),SU_NAME(K),SU_RA(K),SU_DEC(K),
	1            SU_CAL(K),SU_RAD(K),SU_DECD(K)
	      N_SU=N_SU+1
	    END IF
	  END DO
	  JS=WNFRD(FCA,2560,ICHR,FCAPT)		!READ BLOCK
	  FCAPT=FCAPT+2560			!UPDATE PTR
	  DO I1=1,32				!SET CHAR,
	    CALL WNGMTS(80,ICHR(1,I1),M(I1))
	  END DO
	  II=0
	END DO
 998	CONTINUE
	SU_FOUND=.TRUE.
C
	RETURN
C
C NATRFG
C
	ENTRY NATRFG(FCA,FCAPT,M,II)
C
	N_FG=0
	DO WHILE (.TRUE.)
	  DO K=II+1,32
	    IF (NCARD.LT.0) THEN
	      CARD(-NCARD)=M(K)
	      NCARD=NCARD-1
	    END IF
	    IF (M(K)(1:8).EQ.'ENDTABLE') THEN
	      II=K
	      GOTO 997
	    ELSE IF ( M(K)(1:8).EQ.'HEADER' ) THEN
	    ELSE IF ( M(J)(1:8).EQ.'COMMENT') THEN
	    ELSE
	      READ(M(K),'(I2,2(1X,I2),2(1X,F8.1),2(1X,I2),
	1            2(1X,I4),2(1X,I1),A24)') J,
	1            FG_ANT(1,J),FG_ANT(2,J),FG_UT(1,J),FG_UT(2,J),
	1            FG_IF(1,J),FG_IF(2,J),FG_CHAN(1,J),FG_CHAN(2,J),
	1            FG_STOK(1,J),FG_STOK(2,J),FG_REASON
	      N_FG=N_FG+1
	    END IF
	  END DO
	  JS=WNFRD(FCA,2560,ICHR,FCAPT)		!READ BLOCK
	  FCAPT=FCAPT+2560			!UPDATE PTR
	  DO I1=1,32				!SET CHAR,
	    CALL WNGMTS(80,ICHR(1,I1),M(I1))
	  END DO
	  II=0
	END DO
 997	CONTINUE
	FG_FOUND=.TRUE.
C
	RETURN
C
C NATRAN
C
	ENTRY NATRAN(FCA,FCAPT,M,II)
C
	NANT=0
	DO WHILE (.TRUE.)
	  DO J=II+1,32
	    IF (NCARD.LT.0) THEN
	      CARD(-NCARD)=M(J)
	      NCARD=NCARD-1
	    END IF
	    IF (M(J)(1:8).EQ.'ENDTABLE') THEN
	      II=J
	      GOTO 996
	    ELSE IF (M(J)(1:8).EQ.'HEADER' ) THEN
	    ELSE IF (M(J)(1:8).EQ.'COMMENT') THEN
	    ELSE
	      NANT=NANT+1
	      READ(M(J),100) ANT_NUM(NANT),STA(NANT),
	1            ANT_MOUNT(NANT),X(NANT),Y(NANT),Z(NANT),
	1            IAXIS_OFFSET
	      AXIS_OFFSET(NANT)=IAXIS_OFFSET/1000.0
	    END IF
	  END DO
	  JS=WNFRD(FCA,2560,ICHR,FCAPT)		!READ BLOCK
	  FCAPT=FCAPT+2560			!UPDATE PTR
	  DO I1=1,32				!SET CHAR,
	    CALL WNGMTS(80,ICHR(1,I1),M(I1))
	  END DO
	  II=0
	END DO
 996	CONTINUE
	AN_FOUND=.TRUE.
C
	RETURN
C
C NATRMT
C
	ENTRY NATRMT(FCA,FCAPT,M,II)
C
	N_MT=0
	DO WHILE (.TRUE.)
	  DO J=II+1,32
	    IF (NCARD.LT.0) THEN
	      CARD(-NCARD)=M(J)
	      NCARD=NCARD-1
	    END IF
	    IF (M(J)(1:8).EQ.'ENDTABLE') THEN
	      II=J
	      GOTO 995
	    ELSE IF (M(J)(1:8).EQ.'HEADER' ) THEN
	    ELSE IF (M(J)(1:8).EQ.'COMMENT') THEN
	    ELSE
	      N_MT=N_MT+1
	      READ(M(J),101) MT_ANT(N_MT),MT_UT(N_MT),
	1            MT_PRESS(N_MT),MT_TEMP(N_MT),MT_HUMID(N_MT)
	    END IF
	  END DO
	  JS=WNFRD(FCA,2560,ICHR,FCAPT)		!READ BLOCK
	  FCAPT=FCAPT+2560			!UPDATE PTR
	  DO I1=1,32				!SET CHAR,
	    CALL WNGMTS(80,ICHR(1,I1),M(I1))
	  END DO
	  II=0
	END DO
 995	CONTINUE
 	MT_FOUND=.TRUE.
C
	RETURN
C
C NATRCU
C
	ENTRY NATRCU(FCA,FCAPT,M,II)
C
	N_CU=0
	DO WHILE (.TRUE.)
	  DO J=II+1,32
	    IF (NCARD.LT.0) THEN
	      CARD(-NCARD)=M(J)
	      NCARD=NCARD-1
	    END IF
	    IF (M(J)(1:8).EQ.'ENDTABLE') THEN
	      II=J
	      GOTO 994
	    ELSE IF (M(J)(1:8).EQ.'HEADER' ) THEN
	    ELSE IF (M(J)(1:8).EQ.'COMMENT') THEN
	    ELSE
	      N_CU=N_CU+1
	      READ(M(J),102) CU_UT(N_CU),CU_ANT(N_CU),CU_IF(N_CU),
	1            CU_CAL1(N_CU),CU_CAL2(N_CU),CU_CH1(N_CU),
	1            CU_CH2(N_CU)
	    END IF
	  END DO
	  JS=WNFRD(FCA,2560,ICHR,FCAPT)		!READ BLOCK
	  FCAPT=FCAPT+2560			!UPDATE PTR
	  DO I1=1,32				!SET CHAR,
	    CALL WNGMTS(80,ICHR(1,I1),M(I1))
	  END DO
	  II=0
	END DO
 994	CONTINUE
	CU_FOUND=.TRUE.
C
	RETURN
C
C FORMATS
C
 100	FORMAT (I2,1X,A8,1X,I1,3(1X,F13.3),1X,I4)
 101	FORMAT (I2,1X,F8.1,1X,F6.1,2(1X,F4.1))
 102	FORMAT (F8.1,1X,I2,1X,I2,2(1X,F6.1),2(1X,I4))
C
C
	END
