c+ NATXST.FOR
C  WNB 920506
C
C  Revisions:
C
	LOGICAL FUNCTION NATXST(FCA,FCAPT,BUFPTR,BUFFER)
C
C  Skip to recognisable data (based on SKIPTHRU)
C
C  Result:
C
C	NATXST_L = NATXST( FCA_J:I, FCAPT_J:IO, BUFPTR_J:IO, BUFFER_E(640):O)
C				Skip through data to look for recognisable
C				data.
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'RPF_DEF'	!RPFITS DATA AREA
C
C  Parameters:
C
	INTEGER SS$_ENDOFFILE	!EOF INDICATOR
	  PARAMETER (SS$_ENDOFFILE='870'X)
C
C  Arguments:
C
	INTEGER FCA		!FILE
	INTEGER FCAPT		!FILE POINTER
	INTEGER BUFPTR		!BUFFER PTR
	REAL BUFFER(640)	!DATA BUFFER
C
C  Entry points:
C
C
C  Function references:
C
	LOGICAL WNFRD		!READ DATA
	INTEGER NATXSF		!CHECK FOR SIMPLE OR FG TABLE
	INTEGER NATXCJ		!MAKE J
	INTEGER WNGGJ		!DO AS IF J
	REAL NATXCE		!MAKE E
	LOGICAL NATXIB		!CHECK BASELINE
C
C  Data declarations:
C
	INTEGER BASEL		!BASELINE
	REAL RBASE		!BASELINE
	INTEGER IFNO		!IF
	REAL UT,U,V,W		!COORDINATES
C-
	NATXST=.FALSE.					!ASSUME ERROR
	DO WHILE(.TRUE.)				!LOOP THROUGH FILE
C
C First read a new block, since remains of old one is unlikely to
C contain anything useful (and at most one integration)
C
	  IF (.NOT.WNFRD(FCA,2560,BUFFER,FCAPT)) THEN	!READ A BLOCK
	    IF (E_C.EQ.SS$_ENDOFFILE) THEN		!EOF SEEN
	      E_C=3
C
	      RETURN
	    END IF
	    CALL WNCTXT(F_TP,'Unable to read next block')
	    E_C=-1					!ERROR TYPE
C
	    RETURN
	  END IF
	  FCAPT=FCAPT+2560				!UPDATE PTR
C
C Check to see if it's a header block
C
	  E_C=NATXSF(FCA,FCAPT,BUFFER)
	  IF (E_C.NE.0) THEN
	    FCAPT=FCAPT-2560				!RE-READ
	    NATXST=.TRUE.				!FOUND HEADER
C
	    RETURN
	  END IF
	  BUFPTR=1
C
C Skip through the block looking for something legal
C
	  DO WHILE (BUFPTR.LE.632)
	    U       =NATXCE(BUFFER(BUFPTR))
	    V       =NATXCE(BUFFER(BUFPTR+1))
	    W       =NATXCE(BUFFER(BUFPTR+2))
	    RBASE   =NATXCE(BUFFER(BUFPTR+3))
	    UT      =NATXCE(BUFFER(BUFPTR+4))
	    IFNO    =NATXCJ(WNGGJ(BUFFER(BUFPTR+7)))
	    IF (.NOT.NATXIB(RBASE,IFNO,UT,U,V,W)) THEN
	      BASEL=NINT(RBASE)
	      NATXST=.TRUE.				!FOUND DATA
	      E_C=-2
C
	      RETURN
	    END IF
	    BUFPTR=BUFPTR+1
	  END DO
C
C OK lets do it all again
C
	END DO
C
	RETURN
C
C
	END
