C+ NFIDAT.FOR
C  WNB 940216
C
C  Revisions:
C	CMV 940926	Close old file before asking new one
C       WNB 950704	General update
C
	SUBROUTINE NFIDAT
C
C  Get NFILT program parameters
C
C  Result:
C
C	CALL NFIDAT	will ask and set all program parameters
C
C  PIN references:
C
C	OPTION
C       SCN_LOOPS
C       SCN_SETS
C       POLY_DEGREE
C       FREQ_SELECT
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'CBITS_DEF'
	INCLUDE 'SSH_O_DEF'             !SET STRUCTURE DEFINITION
	INCLUDE 'STH_O_DEF'               !SET HEADER
	INCLUDE 'NFI_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
C
C  Function references:
C
	LOGICAL WNDPAR			!GET DWARF PARAMETER
	LOGICAL WNDXLP                  !GET LOOPS
	LOGICAL WNDSTQ                  !GET SET DEFINITIONS
	LOGICAL WNDNOD                  !GET NODE INFO
	LOGICAL WNFOP                   !OPEN FILE
	LOGICAL NSCSTG                  !GET SET
	LOGICAL NSCPLS			!ASK POL
	LOGICAL NSCHAS			!ASK HA RANGE
	LOGICAL NSCIFS			!ASK IFRS
C
C  Data declarations:
C
	INTEGER STHP                    !SET POINTER
	INTEGER SETNAM(0:SOF__N-1)	!SET NAME
	INTEGER CIFR			!IFR SELECTOR CODE
	BYTE STH(0:STH__L-1)		!SET HEADER
C-
C
C SET DEFAULTS
C
	SETS(0,0)=0
	CIFR=2					!ASK ALL CROSS IFR
	HARAN(0)=-179.99/360.			!HA RANGE
	HARAN(1)=+179.99/360.
	SPOL=XYX_M				!POL. SELECTION
C
C GET OPTION
C
 100	CONTINUE
	IF (.NOT.WNDPAR('OPTION',OPTION,LEN(OPTION),J0,'QUIT')) THEN
	  OPTION='QUIT'				!ASSUME END
	ELSE IF (J0.LE.0) THEN
	  OPTION='QUIT'				!ASSUME END
	END IF

C*****************************************************************************
C QUIT
C*****************************************************************************
	IF (OPT.EQ.'QUI') THEN

C ****************************************************************************
C CONTINUUM (UVLIN)
C ****************************************************************************
	ELSE IF (OPT.EQ.'CON') THEN		!UVLIN
 10	   CONTINUE
	   CALL WNFCL(FCAOUT)
	   IF (.NOT.WNDNOD('SCN_NODE',NODOUT,'SCN','U',NODOUT,FILOUT)) THEN
	      IF (E_C.EQ.DWC_ENDOFLOOP) GOTO 100 !RETRY OPTION
	      GOTO 10				!REPEAT
	   ELSE IF (E_C.EQ.DWC_NULLVALUE) THEN
	      GOTO 100				!RETRY OPTION
	   ELSE IF (E_C.EQ.DWC_WILDCARD) THEN
	      GOTO 10				!MUST SPECIFY
	   END IF
	   IF (.NOT.WNFOP(FCAOUT,FILOUT,'U')) THEN !OPEN OUTPUT SCAN FILE
	      GOTO 10				!RETRY
	   END IF
C       
 11	   CONTINUE
	   IF (.NOT.WNDXLP('SCN_LOOPS',FCAOUT)) THEN
	      IF (E_C.EQ.DWC_ENDOFLOOP) GOTO 10	!RETRY NODE
	      GOTO 11				!REPEAT
	   END IF
C       
	   IF (.NOT.WNDSTQ('SCN_SETS',MXNSET,SETS,FCAOUT)) THEN !NO SETS
 12	      CONTINUE
	      CALL WNFCL(FCAOUT)
	      GOTO 10
	   END IF
	   IF (SETS(0,0).EQ.0) GOTO 12 		!NONE SPECIFIED
	   IF (.NOT.NSCSTG(FCAOUT,SETS,STH,STHP,SETNAM)) GOTO 12 !FIND A SET
	   CALL WNDSTR(FCAOUT,SETS) 		!RESET SET SEARCH
C       
	   IF (.NOT.NSCPLS(0,SPOL)) GOTO 12 	!SELECT POL
C       
	   CALL NMODAX(NSRC(0))	!GET MODEL
	   IF (NSRC(0).GT.0) CALL NMOMUI 	!MODEL USAGE
C       
	   IF (.NOT.NSCHAS(0,HARAN)) GOTO 12 	!GET HA RANGE
C       
	   IF (.NOT.NSCIFS(CIFR,SIFRS)) GOTO 12	!SELECT INTERFEROMETERS
	   CIFR=0				!SET SEEN
C       
	   CALL NSCSAD(CORAP,CORDAP) 		!GET CORRECTIONS (DE-)APPLY
C
 13	   CONTINUE
	   IF (.NOT.WNDPAR('FREQ_SELECT',FSEL,2*MXSEL*LB_E,J0,
	1	'*')) THEN			!SELECT FREQ. RANGE
	      IF (E_C.EQ.DWC_ENDOFLOOP) GOTO 12
	      GOTO 13
	   END IF
	   IF (J0.EQ.0) GOTO 13
	   IF (J0.LT.0) THEN
	      FSEL(0,0)=0
	      FSEL(1,0)=1E9
	      J0=2
	   END IF
	   NSEL=J0/2
	   IF (NSEL.LT.1) GOTO 13
C
	   IF (.NOT.WNDPAR('POLY_DEGREE',NPOLY,LB_J,J0,
	1	'1')) THEN
	      GOTO 13
	   END IF
	   IF (J0.EQ.0) GOTO 13
	   IF (J0.LT.0) NPOLY=1
	   NPOLY=MIN(MAX(NPOLY,0),MXPOLY)
C
C
	ELSE
	   GOTO 100
	END IF
C       
 900	CONTINUE
	RETURN					!READY
C
C
	END
