C+ NMOMSG.FOR
C  WNB 900903
C
C  Revisions:
C
	SUBROUTINE NMOMSG(SETSX)
C
C  Get model from scan file
C
C  Result:
C
C	CALL NMOMSG( SETSX_J(0:*):I)	will get a model from scan file
C
C  PIN references
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NMO_DEF'
	INCLUDE 'MDH_O_DEF'		!MODEL HEADER
	INCLUDE 'MDL_O_DEF'		!SOURCE LINE
	INCLUDE 'STH_O_DEF'		!SET HEADER
C
C  Entries:
C
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER SETSX(0:*)		!SETS TO DO
C
C  Function references:
C
	LOGICAL NMORDX			!READ MODEL
	LOGICAL NMORDM			!AND SET IN GENERAL
	LOGICAL NSCSTG			!GET A SET
C
C  Data declarations:
C
	INTEGER STHP			!SET HEADER POINTER
	INTEGER SNAM(0:7)		!SET NAME
	BYTE STH(0:STHHDL-1)		!SET HEADER
	  INTEGER STHJ(0:STHHDL/4-1)
	  EQUIVALENCE (STH,STHJ)
C-
C
C FIND A SET
C
	DO WHILE (NSCSTG(FCAIN,SETSX,STH,STHP,SNAM))
	  IF (STHJ(STH_MDL_J).NE.0) THEN		!THIS ONE
	    IF (NMORDX(FCAIN,STHJ(STH_MDL_J),7)) THEN	!FOUND
	      IF (NMORDM(7,-1)) GOTO 800		!READY
	    END IF
	  END IF
	END DO
	CALL WNCTXT(F_TP,'!/No model found')
C
C READY
C
 800	CONTINUE
	CALL WNFCL(FCAIN)				!CLOSE FILE
C
	RETURN
C
C
	END
