C+ NMOMST.FOR
C  WNB 900903
C
C  Revisions:
C	WNB 931008	Add MINST
C	CMV 940111	Use A_OB in stead of A_OJ
C
	SUBROUTINE NMOMST(BTP,RA,DEC,STHD,LM0,FRQ0,TF,MINST)
C
C  Calculate set dependent data for model calculation
C
C  Result:
C
C	CALL NMOMST( BTP_J:I, RA_D:I, DEC_D:I, STHD_D(0:*):I,
C			LM0_E(0:1):O, FRQ0_D:O, TF_E(0:1):O, MINST_J:O)
C				Calculate for BTP (0=unknown, 1=apparent,
C				2=B1950) the LM0 l,m offset, FRQ0 the
C				frequency to use, TF the smearing parameters,
C				using the set header STHD and the RA, DEC
C				of map; MINST the instrument
C
C  PIN references
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'STH_O_DEF'	!SET HEADER
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER BTP		!COORD. TYPE
	DOUBLE PRECISION RA	!RA TO USE
	DOUBLE PRECISION DEC	!DEC TO USE
	DOUBLE PRECISION STHD(0:*) !SET HEADER
	REAL LM0(0:1)		!L,M OFFSET
	DOUBLE PRECISION FRQ0	!FREQUENCY
	REAL TF(0:1)		!SMEARING PARAM.
	INTEGER MINST		!INSTRUMENT
C
C  Function references:
C
	INTEGER WNGARA		!ADDRESS
C
C  Data declarations:
C
C-
	IF (BTP.EQ.2) THEN				!B1950
	    FRQ0=STHD(STH_FRQE_D)			!CORRECT FREQUENCY
	    CALL WNMCRD(RA,DEC,
	1		LM0(0),LM0(1),
	1		STHD(STH_RAE_D),STHD(STH_DECE_D)) !CORRECT L,M
	ELSE
	  FRQ0=STHD(STH_FRQ_D)				!CORRECT FREQUENCY
	  IF (BTP.EQ.1) THEN				!APPARENT
	    CALL WNMCRD(RA,DEC,
	1		LM0(0),LM0(1),
	1		STHD(STH_RA_D),STHD(STH_DEC_D))	!CORRECT L,M
	  ELSE
	    LM0(0)=0					!NO OFFSET
	    LM0(1)=0
	  END IF
	END IF
	J=(WNGARA(STHD(0))-A_OB)/LB_E			!OFFSET
	TF(0)=A_E(J+STH_HAV_E)				!TIME SMEAR
	TF(1)=A_E(J+STH_BAND_E)				!BAND SMEAR
	J=(WNGARA(STHD(0))-A_OB)/LB_J			!OFFSET
	MINST=A_J(J+STH_INST_J)				!INSTRUMENT
C
	RETURN
C
C
	END
