C+ NSCAN.FOR
C  WNB 900130
C
C  Revisions:
C	WNB 910828	Add RUN
C	WNB 911031	Add WERR
C	WNB 921221	Add AERR
C	WNB 930608	Add FLAG
C	WNB 930619	Remove SHOW and FLAG
C	WNB 930707	Add COPY
C	WNB 930819	Add NOPT
C	HjV 930922	Add SHOW again
C	CMV 931220	Replace copy by message about NCOPY
C	CMV 940223	New option LIST
C	CMV 941012	New option WARC
C	JPH 941207	All options return to NSCDAT, only exit is through QUIT
C	JPH 941207	Close FCAIN, FCAOUT before NSCDAT (write-protect 
C			 problem)
C	HjV 950116	Add LEIDEN, change LOADIF in IFLOAD
C	HjV 951113	Change option WARC into ARC. Result is in LARC/WARC
C
	SUBROUTINE NSCAN
C
C  Main routine to handle Scan files
C
C  Result:
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NSC_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
C
C  Function references:
C
	LOGICAL WNDRUN		!TEST RUN
C
C  Data declarations:
C
C-
C
C PRELIMINARIES
C
	CALL NSCINI				!INIT PROGRAM
C
C DISTRIBUTE
C
 10	CONTINUE
	CALL WNFCL(FCAIN)
	CALL WNFCL(FCAOUT)
	CALL NSCDAT				!GET USER DATA
	IF (.NOT.WNDRUN()) CALL WNGEX		!NO RUN
	IF (OPT.EQ.'QUI') THEN			!READY
	  CALL WNGEX				!FINISH
	ELSE IF (OPT.EQ.'DUM') THEN		!DUMP
	  CALL NSCDMP
	ELSE IF (OPT.EQ.'LOA') THEN		!LOAD
	  CALL NSCLOD(0)
	ELSE IF (OPT.EQ.'IFL') THEN		!IFLOAD
	  CALL NSCLOD(0)
	ELSE IF (OPT.EQ.'WIS') THEN		!WIST (LIST WSRT-tape)
	  CALL NSCLOD(1)
	ELSE IF (OPT.EQ.'WAR') THEN		!WARC (ARC WSRT-tape)
	  CALL NSCLOD(2)
	ELSE IF (OPT.EQ.'LEI') THEN		!LEIDEN
	  CALL NLEIDEN(0)
	ELSE IF (OPT.EQ.'LIS') THEN		!LIST (LIST LEIDEN-tape)
	  CALL NLEIDEN(1)
	ELSE IF (OPT.EQ.'LAR') THEN		!LARC (ARC LEIDEN-tape)
	  CALL NLEIDEN(2)
	ELSE IF (OPT.EQ.'SHO') THEN		!SHOW DATA
	  CALL NFLPRT
	ELSE IF (OPT.EQ.'FRO') THEN		!COPY FROM OLD
	  CALL NSCOFR
	ELSE IF (OPT.EQ.'TO_') THEN		!COPY TO OLD
	  CALL NSCOTO
	ELSE IF (OPT.EQ.'REG') THEN		!REGROUP DATA
	  CALL NSCREG
	ELSE IF (OPT.EQ.'UVF') THEN		!WRITE UVFITS
	  CALL NSCUVF
	ELSE IF (OPT.EQ.'PFI') THEN		!PRINT UVFITS
	  CALL NSCPUV
	ELSE IF (OPT.EQ.'CVX') THEN		!CONVERT VAX TO LOCAL
	  CALL NSCCVX
	ELSE IF (OPT.EQ.'NVS') THEN		!MAKE NEWEST VERSION
	  CALL NSCNVS
	ELSE IF (OPT.EQ.'NOP') THEN		!MAKE NEWEST OPTIONS
	  CALL NSCNOP
	ELSE IF (OPT.EQ.'WE0') THEN		!CORRECT MOSAIC TAPE ERROR
	  CALL NSCWE0
	ELSE IF (OPT.EQ.'WE1') THEN		!CORRECT MOSAIC TAPE ERROR
	  CALL NSCWE1
	ELSE IF (OPT.EQ.'AER') THEN		!CORRECT SIGN PHASE
	  CALL NSCWE2
	ELSE IF (OPT.EQ.'VFI') THEN		!RECALC VELOCITIES
	  CALL NSCWE3
	END IF
C
	GOTO 10					!BACK TO OPTIONS= PROMPT
C
	END
