C+ NSCQS0.FOR
C  WNB 940216
C
C  Revisions:
C
	INTEGER FUNCTION NSCQS0(LD1,LD2)
C
C  Sort the Qube list elements
C
C  Result:
C
C	ORDER_J = NSCQS0( LD1_D(*), LD2_D(*)) Increasing frequency
C	ORDER_J = NSCQS1( LE1_E(*), LE2_E(*)) Increasing ha
C	ORDER_J = NSCQS2( LJ1_J(*), LJ2_J(*)) Increasing J-fields
C	ORDER_J = NSCQS3( LE1_E(*), LE2_E(*)) Increasing E-fields
C	ORDER_J = NSCQS4( LD1_D(*), LD2_D(*)) Increasing D-fields
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'QUB_O_DEF'		!QUBE LINE
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER LJ1(0:*)		!ELEMENT 1
	INTEGER LJ2(0:*)		!ELEMENT 2
	REAL LE1(0:*)			!ELEMENT 1
	REAL LE2(0:*)			!ELEMENT 2
	DOUBLE PRECISION LD1(0:*)	!ELEMENT 1
	DOUBLE PRECISION LD2(0:*)	!ELEMENT 2
C
C  Function references:
C
	DOUBLE PRECISION WNGDNF		!NORM ANGLE
C
C  Entry points:
C
	INTEGER NSCQS1,NSCQS2,NSCQS3,NSCQS4 !SORT
C
C  Data declarations:
C
C-
C
C SORT INCREASING FREQUENCY
C
	IF (ABS(LD1(QUB_FRQ_D)-LD2(QUB_FRQ_D)).LT.1D-8) THEN	!EQUAL
	  NSCQS0=0
	ELSE IF (LD1(QUB_FRQ_D).LT.LD2(QUB_FRQ_D)) THEN
	  NSCQS0=-1
	ELSE
	  NSCQS0=+1
	END IF
C
	RETURN
C
C HA
C
	ENTRY NSCQS1(LE1,LE2)
C
	IF (LE1(QUB_HAB_E).EQ.LE2(QUB_HAB_E)) THEN !HA START
	  NSCQS1=0
	ELSE IF (LE1(QUB_HAB_E).EQ.LE2(QUB_HAB_E)) THEN !HA START
	  NSCQS1=-1
	ELSE
	  NSCQS1=+1
	END IF
C
	RETURN
C
C J-FIELDS
C
	ENTRY NSCQS2(LJ1,LJ2)
C
C
	IF (LJ1(QUB_INST_J).EQ.LJ2(QUB_INST_J)) THEN	!EQUAL INSTRUMENT
	  IF (LJ1(QUB_NPOL_J).EQ.LJ2(QUB_NPOL_J)) THEN	!EQUAL NPOL
	    IF (LJ1(QUB_NIFR_J).EQ.LJ2(QUB_NIFR_J)) THEN !EQUAL NIFR
	      IF (LJ1(QUB_SCN_J).EQ.LJ2(QUB_SCN_J)) THEN !EQUAL NSCAN
	        NSCQS2=0
	      ELSE IF (LJ1(QUB_SCN_J).LT.LJ2(QUB_SCN_J)) THEN
	        NSCQS2=-1
	      ELSE
		NSCQS2=+1
	      END IF
	    ELSE IF (LJ1(QUB_NIFR_J).LT.LJ2(QUB_NIFR_J)) THEN !NIFR
	      NSCQS2=-1
	    ELSE
	      NSCQS2=+1
	    END IF
	  ELSE IF (LJ1(QUB_NPOL_J).LT.LJ2(QUB_NPOL_J)) THEN !NPOL
	    NSCQS2=-1
	  ELSE
	    NSCQS2=+1
	  END IF
	ELSE IF (LJ1(QUB_INST_J).LT.LJ2(QUB_INST_J)) THEN !INSTRUMENT
	  NSCQS2=-1
	ELSE
	  NSCQS2=+1
	END IF
C
	RETURN	
C
C E FIELDS
C
	ENTRY NSCQS3(LE1,LE2)
C
	IF (ABS(LE1(QUB_HAI_E)-LE2(QUB_HAI_E)).LT.1E-6) THEN !HA INCREMENT
	  IF (ABS(LE1(QUB_BAND_E)-LE2(QUB_BAND_E)).LT.1E-6) THEN !BAND
	    NSCQS3=0
	  ELSE IF (LE1(QUB_BAND_E).LT.LE2(QUB_BAND_E)) THEN !BAND
	    NSCQS3=-1
	  ELSE
	    NSCQS3=+1
	  END IF
	ELSE IF (LE1(QUB_HAI_E).LT.LE2(QUB_HAI_E)) THEN !HA INCREMENT
	  NSCQS3=-1
	ELSE
	  NSCQS3=+1
	END IF
C
	RETURN	
C
C D FIELDS
C
	ENTRY NSCQS4(LD1,LD2)
C
	IF (ABS(WNGDNF(LD1(QUB_RA_D)-LD2(QUB_RA_D))).LT.1E-6) THEN !RA
	  IF (ABS(LD1(QUB_DEC_D)-LD2(QUB_DEC_D)).LT.1E-6) THEN !DEC
	    NSCQS4=0
	  ELSE IF (LD1(QUB_DEC_D).LT.LD2(QUB_DEC_D)) THEN !DEC
	    NSCQS4=-1
	  ELSE
	    NSCQS4=+1
	  END IF
	ELSE IF (LD1(QUB_RA_D).LT.LD2(QUB_RA_D)) THEN !RA
	  NSCQS4=-1
	ELSE
	  NSCQS4=+1
	END IF
C
	RETURN	
C
C
	END
