C+ NSCQWF.FOR
C  WNB 940812
C
C  Revisions:
C
	LOGICAL FUNCTION NSCQWF(QUA,FCA)
C
C  Write actual interferometer errors
C
C  Result:
C
C	NSCQWF_L = NSCQWF_L( QUA_J:I, FCA_J:I)
C			Write Qube scan interferometer errors
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'CBITS_DEF'             !BIT DEFINITIONS
	INCLUDE 'QUB_O_DEF'		!QUBE DEFINITION
	INCLUDE 'STH_O_DEF'		!SCAN SET HEADER
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER QUA			!QUBE CONTROL AREA
	INTEGER FCA			!FILE
C
C  Function references:
C
	LOGICAL NSCQE0			!WRITE A BLOCK
C
C  Data declarations:
C
C-
C
C INIT
C
	NSCQWF=.TRUE.				!ASSUME OK
	IF (IAND(A_J(QUA+QUA_ORDER_J),QUB_OUT).EQ.0)
	1		RETURN			!CANNOT DO
	IF (IAND(A_J(QUA+QUA_ORDER_J),QUB_I).NE.0) THEN !GIVE NORMAL SCAN
	  RETURN				!NOTHING TO DO
	END IF
C
C WRITE DAVED ERRORS
C
	IF (IAND(A_J(QUA+QUA_ORDER_J),
	1		QUB_TIF+QUB_FIT).NE.0) THEN !TIF/FIT
	  IF (A_J(QUA+QUA_CIMAP_J).LT.0) RETURN	!NOTHING TO DO
	  IF (.NOT.NSCQE0(QUA,FCA,A_J(QUA+QUA_CIMAP_J),0)) THEN
 10	    NSCQWF=.FALSE.
	    RETURN
	  END IF
	ELSE IF (IAND(A_J(QUA+QUA_ORDER_J),
	1		QUB_ITF+QUB_IFT).NE.0) THEN !ITF/IFT
	  DO I=0,A_J(QUA+QUA_CICNT_J)-1		!DO ALL BLOCKS
	    IF (.NOT.NSCQE0(QUA,FCA,I,
	1		A_J(A_J(QUA+QUA_CIPMAP_J)+I)-1)) GOTO 10
	  END DO
	END IF
C
	RETURN
C
C
	END
