C+ NSCQC0.FOR
C  WNB 940729
C
C  Revisions:
C
	INTEGER FUNCTION NSCQC0(LB1,LB2)
C
C  Compare the Qube list elements
C
C  Result:
C
C	ORDER_J = NSCQC0( LB1_B(*):I, LB2_B(*):I) Compare Qube lines
C	ORDER_J = NSCQC1( LB1_B(*):I, LB2_B(*):I) Compare Qube Field lines
C	ORDER_J = NSCQC2( LB1_B(*):I, LB2_B(*):I) Compare Qube freq lines
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'QUB_O_DEF'		!QUBE LINE
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER LB1(0:*)		!ELEMENT 1
	INTEGER LB2(0:*)		!ELEMENT 2
C
C  Entry points:
C
	INTEGER NSCQC1,NSCQC2
C
C  Function references:
C
	INTEGER NSCQS0                  !COMPARE FREQUENCY
	INTEGER NSCQS1                  !COMPARE HA
	INTEGER NSCQS2                  !COMPARE J FIELDS
	INTEGER NSCQS3                  !COMPARE E
	INTEGER NSCQS4                  !COMPARE D
C
C  Data declarations:
C
C-
C
C NSCQC0
C
	NSCQC0=NSCQS4(LB1,LB2)          !COMPARE
	IF (NSCQC0.EQ.0) THEN
	  NSCQC0=NSCQS3(LB1,LB2)
	  IF (NSCQC0.EQ.0) THEN
	    NSCQC0=NSCQS2(LB1,LB2)
	    IF (NSCQC0.EQ.0) THEN
	      NSCQC0=NSCQS1(LB1,LB2)
	      IF (NSCQC0.EQ.0) THEN
	        NSCQC0=NSCQS0(LB1,LB2)
	      END IF
	    END IF
	  END IF
	END IF
C
	RETURN
C
C NSCQC1
C
	ENTRY NSCQC1(LB1,LB2)
C
	NSCQC1=NSCQS4(LB1,LB2)          !COMPARE
	IF (NSCQC1.EQ.0) THEN
	  NSCQC1=NSCQS3(LB1,LB2)
	  IF (NSCQC1.EQ.0) THEN
	    NSCQC1=NSCQS2(LB1,LB2)
	  END IF
	END IF
C
	RETURN
C
C NSCQC2
C
	ENTRY NSCQC2(LB1,LB2)
C
	NSCQC2=NSCQS0(LB1,LB2)          !COMPARE
C
	RETURN
C
C
	END
