C+ NMOBMV.FOR
C  WNB 930826
C
C  Revisions:
C	CMV 930917	Various corrections, changed direction of change
C	CMV 930921	Changed direction back
C	WNB 930928	Split off from NMOBMF
C
	DOUBLE PRECISION FUNCTION NMOBMV(FRQ,L,M,BEMLIM,DEB)
C
C  Get beam value
C
C  Result:
C
C	NMOBMV_D = NMOBMV( FRQ_D:I, L_E:I, M_E:I,
C				BEMLIM_D:I, DEB_L:I)
C				Get value for frequency and l,m using
C				the NMOBMF obtained data, lower limit BEMLIM
C				and if DEBeam.
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'BMD_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	DOUBLE PRECISION FRQ	!FREQUENCY (MHZ)
	REAL L			!L (RADIANS)
	REAL M			!M (RADIANS)
	DOUBLE PRECISION BEMLIM	!LOWEST LIMIT
	LOGICAL DEB		!DEBEAM
C
C  Function references:
C
C
C  Data declarations:
C
C-
	R1=BEMSC*FRQ				!SCALING
	R0=(L**2+M**2)*(R1**2)			!ANGLE ON SKY (RADIANS)
	IF (BEMCOD(1,BEMCIN).EQ.0) THEN		!COS^6
	  D0=COS(BEMFC(BEMCFP,BEMCIN)*SQRT(R0))**6 !BEAM VALUE
	ELSE
	  R0=R0*((DEG*60/1000)**2)		!MAKE ARCMIN.GHZ
	  D0=BEMFC(BEMCFP+BEMCOD(3,BEMCIN)-1,BEMCIN)*R0 !LAST FACTOR
	  DO I=BEMCOD(3,BEMCIN)-2,0,-1		!MAKE SUM
	    D0=(D0+BEMFC(BEMCFP+I,BEMCIN))*R0
	  END DO
	  D0=D0+1D0				!1+AI.X^2I
	  IF (BEMCOD(1,BEMCIN).EQ.1 .AND.
	1		ABS(D0).GE.1D-6) THEN	!1/(1+AI.X^2I)
	    D0=1D0/D0
	  END IF
	END IF
	IF (D0.LT.BEMLIM) D0=BEMLIM
	IF (.NOT.DEB .AND. ABS(D0).GE.1D-6) D0=1/D0 !DEBEAM
	NMOBMV=D0				!RETURN VALUE
C
	RETURN
C
C
	END
