C+ NMOHED.FOR
C  WNB 900827
C
C  Revisions:
C	WNB 910809	Add HMT, HMF
C	JPH 940224	Typo in comment
C
C
	SUBROUTINE NMOHCD(IDESJ)
C
C  Act on model header data
C
C  Result:
C
C	CALL NMOHCD( IDESJ_J(0:*):IO)
C			will clear data part of header
C	CALL NMOHZD( IDESJ_J(0:*):IO)
C			will clear data part of header and # of sources
C	CALL NMOHMD( IDESJ_J(0:*):I, ODESJ_J(0:*):O)
C			will move data part from I to O
C	CALL NMOHMF( IDX_J:I, ODESJ_J(0:*):O)
C			will move header from general header IDX to ODESJ
C	CALL NMOHMT( IDESJ_J(0:*):I, ODX_J:O)
C			will move header from IDESJ to general header ODX
C
C  PIN references
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'MDH_O_DEF'			!MODEL HEADER
	INCLUDE 'NMO_DEF'
C
C  Entries:
C
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER IDESJ(0:*)			!INPUT HEADER
	INTEGER ODESJ(0:*)			!OUTPUT HEADER
	INTEGER IDX				!INPUT GENERAL HEADER
	INTEGER ODX				!OUTPUT GENERAL HEADER
C
C  Function references:
C
C
C  Data declarations:
C
C-
C
C CLEAR DATA
C
	CALL WNGMVZ(MDHHDL-MDH_TYP_1,IDESJ(MDH_TYP_J))
C
	RETURN
C
C ZERO DATA
C
	ENTRY NMOHZD(IDESJ)
C
	CALL WNGMVZ(MDHHDL-MDH_TYP_1,IDESJ(MDH_TYP_J))
	IDESJ(MDH_NSRC_J)=0			!NO SOURCES
C
	RETURN
C
C MOVE DATA
C
	ENTRY NMOHMD(IDESJ,ODESJ)
C
	CALL WNGMV(MDHHDL-MDH_TYP_1,IDESJ(MDH_TYP_J),
	1		ODESJ(MDH_TYP_J))
C
	RETURN
C
C MOVE FROM GENERAL
C
	ENTRY NMOHMF(IDX,ODESJ)
C
	CALL WNGMV(MDHHDL,GMDH(0,IDX),ODESJ)
C
	RETURN
C
C MOVE TO GENERAL
C
	ENTRY NMOHMT(IDESJ,ODX)
C
	CALL WNGMV(MDHHDL,IDESJ,GMDH(0,ODX))
C
	RETURN
C
C
	END
