C+ NMOMUP.FOR
C  WNB 900903
C
C  Revisions:
C	WNB 920320	SUN cannot handle empty argument functions
C
	LOGICAL FUNCTION NMOMUP()
C
C  Prepare model for scan insertion
C
C  Result:
C
C	NMOMUP_L = NMOMUP()	will prepare model for scan insertion
C
C  PIN references
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NMO_DEF'
	INCLUDE 'MDH_O_DEF'		!MODEL HEADER
	INCLUDE 'MDL_O_DEF'		!MODEL LINE
C
C  Entries:
C
C
C  Parameters:
C
C
C  Arguments:
C
C
C  Function references:
C
	LOGICAL NMOSLG				!GET MODEL AREA
C
C  Data declarations:
C
C-
C
C INIT
C
	NMOMUP=.TRUE.				!ASSUME OK
C
C GET AREAS 
C
	CALL NMOHZD(GMDH(0,0))			!CLEAR TYPE 0
	CALL NMOHMD(GDES,GMDH(0,0))		!SET DATA
	CALL NMOHZD(GMDH(0,1))			!CLEAR TYPE 1
	CALL NMOHMD(GDES,GMDH(0,1))		!SET DATA
	CALL NMOHZD(GMDH(0,2))			!CLEAR OTHER TYPES
	CALL NMOHMD(GDES,GMDH(0,2))		!SET DATA
	IF (GDESJ(MDH_NSRC_J).GT.0) THEN	!SPLIT SOURCES
	  IF (.NOT.NMOSLG(GDESJ(MDH_NSRC_J),GMDH(0,0))) GOTO 900 !GET SPACE
	  IF (.NOT.NMOSLG(GDESJ(MDH_NSRC_J),GMDH(0,1))) GOTO 900
	  IF (.NOT.NMOSLG(GDESJ(MDH_NSRC_J),GMDH(0,2))) GOTO 900
C
C SET SOURCES IN SEPARATE LISTS
C
	  CALL NMOAMG				!MERGE SOURCE LIST
	  CALL NMOSRT(1,GDES)			!SORT LIST ON L,M
	  J0=GDESJ(MDH_MODP_J)-A_OB		!ARRAY OFFSET
	  DO I=0,GDESJ(MDH_NSRC_J)-1		!ALL SOURCES
	    IF (A_B(J0+MDL_TP1_B).EQ.0) THEN	!TYPE 0
	      CALL WNGMV(MDLHDL,A_B(J0),A_B(GMDHJ(MDH_MODP_J,0)+
	1		GMDHJ(MDH_NSRC_J,0)*MDLHDL-A_OB)) !SET SOURCE
	      GMDHJ(MDH_NSRC_J,0)=GMDHJ(MDH_NSRC_J,0)+1 !COUNT SOURCE
	    ELSE IF (A_B(J0+MDL_TP1_B).EQ.1) THEN !TYPE 1
	      CALL WNGMV(MDLHDL,A_B(J0),A_B(GMDHJ(MDH_MODP_J,1)+
	1		GMDHJ(MDH_NSRC_J,1)*MDLHDL-A_OB)) !SET SOURCE
	      GMDHJ(MDH_NSRC_J,1)=GMDHJ(MDH_NSRC_J,1)+1 !COUNT SOURCE
	    ELSE				!OTHER TYPES
	      CALL WNGMV(MDLHDL,A_B(J0),A_B(GMDHJ(MDH_MODP_J,2)+
	1		GMDHJ(MDH_NSRC_J,2)*MDLHDL-A_OB)) !SET SOURCE
	      GMDHJ(MDH_NSRC_J,2)=GMDHJ(MDH_NSRC_J,2)+1 !COUNT SOURCE
	    END IF
	    J0=J0+MDLHDL			!NEXT SOURCE
	  END DO
	END IF
C
	RETURN
C
C ERRORS
C
 900	CONTINUE
	CALL WNCTXT(F_TP,'Cannot obtain model lists')
	NMOMUP=.FALSE.
C
	RETURN
C
C
	END
