C+ NMOSRT.FOR
C  WNB 900327
C
C  Revisions:
C
	SUBROUTINE NMOSRT(TP,SDESJ)
C
C  Sort a source list
C
C  Result:
C
C	CALL NMOSRT( TP_J:I, SDESJ_J(0:*):I)
C				Sort the source list described by SDESJ.
C				It will be adjusted for deleted entries.
C					TP=-1  Deleted entreis only
C					TP=0:  Decreasing intensity
C					TP=1:  Decreasing l,m
C					TP=2:  J field
C					TP=3:  E field
C					TP=4:  B field
C					TP=5:  distance
C					TP=6:  l,m
C					TP=7:  m,l
C					TP=8:  polarisation
C					else:  Decreasing intensity
C
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'MDH_O_DEF'			!MODEL HEADER
	INCLUDE 'MDL_O_DEF'			!MODEL LINE
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER TP				!SORTING TYPE
	INTEGER SDESJ(0:*)			!SOURCE LIST HEADER
C
C  Function references:
C
	EXTERNAL NMOSR0,NMOSR1,NMOSR2,NMOSR3,	!SORT ROUTINES
	1		NMOSR4,NMOSR5,NMOSR6,NMOSR7,NMOSR8
C
C  Data declarations:
C
C-
C
C DELETE SOURCES WITH I=0
C
	DO I=SDESJ(MDH_NSRC_J)-1,0,-1		!DELETE SOURCES WITH I=0
	  J1=(SDESJ(MDH_MODP_J)+I*MDLHDL-A_OB)/(L_E/L_B) !ARRAY POINTER
	  IF (A_E(J1+MDL_I_E).EQ.0) THEN
	    DO I1=I+1,SDESJ(MDH_NSRC_J)-1
	      J2=(SDESJ(MDH_MODP_J)+I1*MDLHDL-A_OB) !ARRAY POINTER
	      CALL WNGMV(MDLHDL,A_B(J2),A_B(J2-MDLHDL)) !DO DELETE
	    END DO
	    SDESJ(MDH_NSRC_J)=SDESJ(MDH_NSRC_J)-1
	  END IF
	END DO
C
	IF (SDESJ(MDH_NSRC_J).LT.1) RETURN	!READY
C
C
C NO SORT
C
	IF (TP.EQ.-1) THEN
C
C SORT ON DECREASING INTENSITY
C
	ELSE IF (TP.EQ.0) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR0)	!DO SORT
C
C SORT ON DECREASING L,M
C
	ELSE IF (TP.EQ.1) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR1)	!DO SORT
C
C SORT ON J FIELD
C
	ELSE IF (TP.EQ.2) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR2)	!DO SORT
C
C SORT ON E FIELD
C
	ELSE IF (TP.EQ.3) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR3)	!DO SORT
C
C SORT ON B FIELD
C
	ELSE IF (TP.EQ.4) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR4)	!DO SORT
C
C SORT ON DISTANCE
C
	ELSE IF (TP.EQ.5) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR5)	!DO SORT
C
C SORT ON L,M
C
	ELSE IF (TP.EQ.6) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR6)	!DO SORT
C
C SORT ON M,L
C
	ELSE IF (TP.EQ.7) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR7)	!DO SORT
C
C SORT ON POLARISATION
C
	ELSE IF (TP.EQ.8) THEN
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR8)	!DO SORT
C
C SORT ON DECREASING INTENSITY
C
	ELSE
	  CALL WNGSRT(A_B(SDESJ(MDH_MODP_J)-A_OB),
	1		SDESJ(MDH_NSRC_J),MDLHDL,NMOSR0)	!DO SORT
C
	END IF
C
	RETURN
C
C
	END
