c+ NMOSLI.FOR
C  WNB 900327
C
C  Revisions:
C
	LOGICAL FUNCTION NMOSLI(NGSRC)
C
C  Get general source list
C
C  Result:
C
C	NMOSLI_L = NMOSLI( NGSRC_J:I)	get a general source list of at least
C					NGSRC sources
C	NMOSLG_L = NMOSLG( NGSRC_J:I, SDESJ_J(0:*):IO) get a source list with
C					NGSRC entries, using SDESJ
C	NMOSLD_L = NMOSLD( DSDESJ_J(0:*):IO) delete source list of DSDESJ
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NMO_DEF'
	INCLUDE 'MDH_O_DEF'		!MODEL HEADER
	INCLUDE 'MDL_O_DEF'		!MODEL LINE
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER NGSRC			!# OF SOURCES IN LIST
	INTEGER SDESJ(0:*),DSDESJ(0:*)	!SOURCE LIST HEADER
C
C  Entry points:
C
	LOGICAL NMOSLG			!OBTAIN A SOURCELIST
	LOGICAL NMOSLD			!DELETE A SOURCE LIST
C
C  Function references:
C
	LOGICAL WNGGVM			!GET VIRTUAL MEMORY
C
C  Data declarations:
C
C-
C
C INIT SOURCE LIST
C
	NMOSLI=.TRUE.				!ASSUME OK
	IF (NSRCM.LE.0) THEN			!EMPTY GENERAL HEADER
	  CALL WNGMVZ(8*MDHHDL,GMDH(0,0))	!EMPTY HEADERS
	END IF
	IF (NGSRC.GT.NSRCM) THEN		!GET AN AREA
	  IF(.NOT.WNGGVM(NGSRC*MDLHDL,J)) THEN	!GET SOURCE AREA
 10	    CONTINUE
	    CALL WNCTXT(F_TP,'!Cannot obtain source area')
	    NMOSLI=.FALSE.
	    RETURN
	  END IF
	  J2=GDESJ(MDH_MODP_J)-A_OB		!ARRAY OFFSET OLD AREA
	  J1=J-A_OB				!ARRAY OFFSET NEW AREA
	  CALL WNGMV(GDESJ(MDH_NSRC_J)*MDLHDL,A_B(J2),A_B(J1)) !MOVE SOURCES
	  IF (GDESJ(MDH_MODL_J).GT.0)		!FREE OLD AREA
	1	CALL WNGFVM(GDESJ(MDH_MODL_J)*MDLHDL,GDESJ(MDH_MODP_J))
	  GDESJ(MDH_MODL_J)=NGSRC		!NEW LENGTH
	  GDESJ(MDH_MODP_J)=J			!NEW MODEL AREA
	  NSRCM=NGSRC				!CURRENT LENGTH
	END IF
C
	RETURN					!READY
C
C GET A SOURCE LIST
C
	ENTRY NMOSLG(NGSRC,SDESJ)
C
	NMOSLG=.TRUE.				!ASSUME OK
	IF (NSRCM.LE.0) THEN			!EMPTY GENERAL HEADER
	  CALL WNGMVZ(8*MDHHDL,GMDH(0,0))	!EMPTY HEADERS
	  IF(.NOT.WNGGVM(MDLHDL,J)) THEN	!GET A SOURCE AREA
	    GOTO 10
	  END IF
	  GDESJ(MDH_MODL_J)=1			!SET SOMETHING THERE
	  GDESJ(MDH_MODP_J)=J
	  NSRCM=1
	END IF
	IF (NGSRC.GT.SDESJ(MDH_MODL_J)) THEN	!GET AN AREA
	  IF(.NOT.WNGGVM(NGSRC*MDLHDL,J)) THEN	!GET SOURCE AREA
	    GOTO 10
	  END IF
	  J2=SDESJ(MDH_MODP_J)-A_OB		!ARRAY OFFSET OLD AREA
	  J1=J-A_OB				!ARRAY OFFSET NEW AREA
	  CALL WNGMV(MIN(SDESJ(MDH_MODL_J),SDESJ(MDH_NSRC_J))*
	1		MDLHDL,A_B(J2),A_B(J1))
	  IF (SDESJ(MDH_MODL_J).GT.0)		!FREE OLD
	1	CALL WNGFVM(SDESJ(MDH_MODL_J)*MDLHDL,SDESJ(MDH_MODP_J))
	  SDESJ(MDH_MODL_J)=NGSRC		!NEW LENGTH
	  SDESJ(MDH_MODP_J)=J			!NEW AREA
	END IF
C
	RETURN					!READY
C
C DELETE SOURCE LIST
C
	ENTRY NMOSLD(DSDESJ)
C
	NMOSLD=.TRUE.				!ASSUME OK
	IF (DSDESJ(MDH_MODL_J).GT.0)		!FREE
	1	CALL WNGFVM(DSDESJ(MDH_MODL_J)*MDLHDL,DSDESJ(MDH_MODP_J))
	DSDESJ(MDH_MODL_J)=0			!NEW LENGTH
	DSDESJ(MDH_MODP_J)=0			!NEW AREA
	DSDESJ(MDH_NSRC_J)=0			!NO SOURCES
C
	RETURN
C
C
	END
