C+ NMOWRS.FOR
C  WNB 900327
C
C  Revisions:
C
	LOGICAL FUNCTION NMOWRS(FCA,SDESJ)
C
C  Write a source model
C
C  Result:
C
C	NMOWRS_L = NMOWRS( FCA_J:I, SDESJ_J(0:*):I)
C				Write the source list described by SDESJ
C				to a node. The list will be sorted and merged.
C	NMOWRX_L = NMOWRX( FCA_J:I, SDESJ_J(0:*):I, DAD_J:I)
C				Write the source list to file FCA at DAD. 
C
C  PIN references
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NMO_DEF'
	INCLUDE 'GFH_O_DEF'			!GENERAL FILE HEADER
	INCLUDE 'MDH_O_DEF'			!MODEL HEADER
	INCLUDE 'MDL_O_DEF'			!MODEL LINE
C
C  Entries:
C
	LOGICAL NMOWRX
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER FCA				!FILE TO WRITE TO
	INTEGER SDESJ(0:*)			!MODEL DESCRIPTION
	INTEGER DAD				!DISK ADDRESS
C
C  Function references:
C
	LOGICAL WNFWR				!WRITE TO FILE
	LOGICAL WNDLNK				!LINK ENTITY
C
C  Data declarations:
C
	BYTE MDH(0:MDHHDL-1)			!SOURCE HEADER
	  INTEGER MDHJ(0:MDHHDL/4-1)
	  EQUIVALENCE (MDH,MDHJ)
	INTEGER DPTR				!DISK POINTER
	LOGICAL WRS				!TYPE
C-
C
C WRS
C
	DPTR=GFHHDL					!SET WHERE TO WRITE
	WRS=.TRUE.					!SET TYPE
	GOTO 10
C
C WRX
C
	ENTRY NMOWRX(FCA,SDESJ,DAD)
C
	DPTR=DAD					!SET WHERE TO WRITE
	WRS=.FALSE.					!SET TYPE
	GOTO 10
C
C INIT
C
 10	CONTINUE
	NMOWRS=.TRUE.					!ASSUME OK
	CALL NMOSRT(0,SDESJ)				!SORT MODEL FILE
	CALL WNGMV(MDHHDL,SDESJ,MDH)			!SET HEADER
	MDHJ(MDH_MODL_J)=MDHHDV				!SET VERSION
	MDHJ(MDH_MODP_J)=DPTR+MDHHDL			!DISK POINTER
	MDHJ(MDH_ACT_J)=MODACT				!SAVE ACTION
	IF (.NOT.WNFWR(FCA,MDHHDL,MDH,DPTR)) GOTO 900	!SAVE HEADER
	IF (WRS) THEN
	  IF (.NOT.WNDLNK(GFH_LINK_1,GFHHDL,MDH_MID_1,FCA)) !LINK MODEL HEADER
	1				GOTO 900
	END IF
C
C WRITE SOURCES
C
	J1=MDHJ(MDH_MODP_J)				!OUTPUT POINTER
	J0=SDESJ(MDH_MODP_J)-A_OB			!INPUT ARRAY POINTER
	DO I=0,MDHJ(MDH_NSRC_J)-1			!ALL SOURCES
	  IF (.NOT.WNFWR(FCA,MDLHDL,A_B(J0),J1)) GOTO 900 !WRITE SOURCE
	  J0=J0+MDLHDL					!NEXT INPUT
	  J1=J1+MDLHDL					!NEXT OUTPUT
	END DO
C
	IF (WRS) CALL WNFCL(FCA)			!CLOSE FILE
C
	RETURN
C
C ERRORS
C
 900	CALL WNCTXT(F_TP,'!/Error writing source file')
	NMOWRS=.FALSE.					!INDICATE ERROR
	IF (WRS) CALL WNFCL(FCA)			!CLOSE FILE
C
	RETURN
C
C
	END
