C+ WNCSAD.FOR
C  WNB 880725
C
C  Revisions:
C
	SUBROUTINE WNCSAD(FRST,FRS,FRE,TOST,TOL,TOP)
C
C  Add string to other string
C
C  Result:
C
C	CALL WNCSAD( FRST_C*:I, FRS_J:I, FRE_J:I, TOST_C*:O,
C				TOL_J:I, TOP_J:IO)
C					Add string FRST(FRS:FRE) to TOST with
C					a length TOL at TOP+1, and update TOP.
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	CHARACTER*(*) FRST			!INPUT STRING
	INTEGER FRS				!START STRING TO COPY
	INTEGER FRE				!END FIELD TO COPY
	CHARACTER*(*) TOST			!OUTPUT STRING
	INTEGER TOL				!LENGTH OUTPUT STRING
	INTEGER TOP				!OUTPUT POINTER
C
C  Function references:
C
C
C  Data declarations:
C
C
C  Equivalences:
C
C
C  Commons:
C
C-
	I=LEN(FRST)
	IF (FRS.LE.I .AND. FRE.GE.FRS) THEN	!CAN DO SOMETHING
	  I1=MIN(LEN(TOST),TOL)			!LENGTH OUTPUT
	  IF (TOP.LT.I1) THEN			!CAN OUTPUT SOME
	    I2=MIN(MIN(I-FRS,FRE-FRS),I1-TOP-1)	!LENGTH
	    TOST(TOP+1:TOP+I2+1)=FRST(FRS:FRS+I2) !SET
	    TOP=TOP+I2+1			!NEW POINTER
	  END IF
	END IF
C
	RETURN
C
C
	END
