C+ WNGIN.FOR
C  WNB 890308
C
C  Revisions:
C	WNB 910828	Add ^C handler
C	WNB 910909	Add WNGIN1
C
	SUBROUTINE WNGIN(PRG,VS,PDAT)
C
C  Initialise program
C
C  Result:
C
C	CALL WNGIN ( PRG_C*:I, VS_C*:I, PDAT_J:I)
C				Initialise program. Set PRG program name,
C				VS version and PDAT datatype; open LOG file.
C	CALL WNGIN1		Only initialise dummy arrays
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	CHARACTER*(*) PRG			!PROGRAM NAME
	CHARACTER*(*) VS			!PROGRAM VERSION
	INTEGER PDAT				!PROGRAM DATA TYPE
C
C  Function references:
C
	INTEGER WNGARA				!VARIABLE ADDRESS
C
C  Data declarations:
C
	LOGICAL IN1
C-
	IN1=.FALSE.				!NOT IN1
	GOTO 10
C
C IN1
C
	ENTRY WNGIN1
C
	IN1=.TRUE.
	GOTO 10
C
C INIT WNG_COM
C
 10	CONTINUE
	IF (.NOT.IN1) THEN
	  PRGNAM=PRG				!SAVE PROGRAM NAME
	  PRGVER=VS				!SAVE VERSION
	  PRGDAT=PDAT				!SAVE DATA/MACHINE TYPE
	  LOGCD=F_YES				!SET LOG, NOSPOOL
	ELSE
	  PRGNAM='UNKNOWN'
	  PRGVER='910101'
	  PRGDAT=1				!ASSUME VAX DATA
	END IF
	E_C=1					!NO ERROR
	A_OB=WNGARA(A_B)			!ARRAY OFFSETS
	A_OI=A_OB/LB_I
	A_OJ=A_OB/LB_J
	A_OK=A_OB/LB_K
	A_OL=A_OB/LB_L
	A_OE=A_OB/LB_E
	A_OD=A_OB/LB_D
	A_OX=A_OB/LB_X
	A_OY=A_OB/LB_Y
	IF (.NOT.IN1) THEN
	  CALL WNGSCC				!SET ^C HANDLER
	  CALL WNCFOP(F_P,' ')			!OPEN LOG FILE
	END IF
C
	RETURN
C
C
	END
