C+ WNMCCV.FOR
C  WNB 900827
C
C  Revisions:
C	WNB 911014	Typo in LMRD, RMDL
C	WNB 911025	Add double precision
C	JPH 940930	Comments only
C	WNB 970522	Return indication for non-existant DLRM
C
	SUBROUTINE WNMCLM(RA0,DEC0,L,M,RA,DEC)
C
C  Convert l, m into ra,dec
C
C  Result:
C
C	CALL WNMCLM ( RA0_D:I, DEC0_D:I, L_E:I, M_E:I, RA_D:O, DEC_D:O)
C	     WNMDLM			 LD_D	MD_D
C							L,M to RA,DEC
C
C	CALL WNMCRD ( RA0_D:I, DEC0_D:I, L_E:O, M_E:O, RA_D:I, DEC_D:I)
C	     WNMDRD			 LD_D	MD_D
C							RA,DEC to L,M
C
C	CALL WNMCRM ( RA0_D:I, DEC0_D:I, L_E:O, M_E:I, RA_D:I, DEC_D:O)
C	     WNMDRM			 LD_D	MD_D
C							RA,M to DEC,L
C
C	CALL WNMCDL ( RA0_D:I, DEC0_D:I, L_E:I, M_E:O, RA_D:O, DEC_D:I)
C	     WNMDDL			 LD_D	MD_D
C							DEC,L to RA,M
C							RA=M=-100. if
C							not possible
C	CALL WNMCD2 ( RA0_D:I, DEC0_D:I, L_E:I, M_E:O, RA_D:O, DEC_D:I)
C							Get 2nd m belonging
C							to CDL solution
C
C				All RA, DEC in fractions of circles,
C				l, m in radians
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	REAL*8 RA0					!CENTRE RA
	REAL*8 DEC0					!CENTRE DEC
	REAL L						!L
	REAL*8 LD
	REAL M						!M
	REAL*8 MD
	REAL*8 RA					!RA
	REAL*8 DEC					!DEC
C
C  Function references:
C
	REAL*8 WNGDPR					!NORMALIZE ANGLE (RAD)
C
C  Data declarations:
C
	REAL*8 SIND0,COSD0				!SIN,COS(DEC0)
	REAL*8 SINRA,COSRA				!SIN,COS(RA-RA0)
	REAL*8 SIND,COSD				!SIN,COS(DEC)
	REAL*8 DL,DM
	
C
C  Equivalences:
C
C
C  Commons:
C
C-
C
C LMRD
C
	SIND0=SIN(DEC0*DPI2)
	COSD0=COS(DEC0*DPI2)
	DL=L
	DM=M
	D0=DM*DM*SIND0*SIND0+DL*DL-2*DM*COSD0*SIND0 !CORRECTION
	SIND=SQRT(ABS(SIND0*SIND0-D0))
	COSD=SQRT(ABS(COSD0*COSD0+D0))
	SIND=SIGN(SIND,SIND0)
	DEC=ATAN2(SIND,COSD)/DPI2
	IF (L.NE.0) THEN
	  RA=WNGDPR(ATAN2(-DL,COSD0-DM*SIND0)+RA0*DPI2)/DPI2
	ELSE
	  RA=WNGDPR(ATAN2(1.D-10,COSD0-DM*SIND0)+RA0*DPI2)/DPI2
	END IF
C
	RETURN
C
C RDLM
C
	ENTRY WNMCRD(RA0,DEC0,L,M,RA,DEC)
C
	L=-SIN((RA-RA0)*DPI2)*COS(DEC*DPI2)
	SIND0=SIN(DEC0*DPI2)
	IF (SIND0.NE.0) THEN
	  M=-(COS((RA-RA0)*DPI2)*COS(DEC*DPI2)-COS(DEC0*DPI2))/
	1		SIN(DEC0*DPI2)
	ELSE
	  M=0
	END IF
C
	RETURN
C
C RMDL
C
	ENTRY WNMCRM(RA0,DEC0,L,M,RA,DEC)
C
	COSD0=COS(DEC0*DPI2)
	SIND0=SIN(DEC0*DPI2)
	COSRA=COS((RA-RA0)*DPI2)
	SINRA=SIN((RA-RA0)*DPI2)
	DM=M
	IF (COSRA.NE.0) THEN
	  DL=(DM*SIND0-COSD0)*SINRA/COSRA
	ELSE
	  DL=0
	END IF
	D0=DM*DM*SIND0*SIND0+DL*DL-2*DM*COSD0*SIND0 !CORRECTION
	SIND=SQRT(ABS(SIND0*SIND0-D0))
	COSD=SQRT(ABS(COSD0*COSD0+D0))
	SIND=SIGN(SIND,SIND0)
	DEC=ATAN2(SIND,COSD)/DPI2
	L=DL
C
	RETURN
C
C DLRM
C
	ENTRY WNMCDL(RA0,DEC0,L,M,RA,DEC)
C
	SIND0=SIN(DEC0*DPI2)
	COSD0=COS(DEC0*DPI2)
	COSD=COS(DEC*DPI2)
	DL=L
	IF (COSD.NE.0) THEN
	  SINRA=-DL/COSD
	ELSE
	  SINRA=0
	END IF
	IF (SINRA.GT.1.0) THEN
	  M=-100.
	  RA=-100.
	ELSE
	  COSRA=SQRT(ABS(1D0-SINRA*SINRA))
	  IF (SINRA.NE.0) THEN
	    RA=WNGDPR(ATAN2(SINRA,COSRA)+RA0*DPI2)/DPI2
	  ELSE
	    RA=WNGDPR(ATAN2(1.D-10,COSRA)+RA0*DPI2)/DPI2
	  END IF
	  IF (SIND0.NE.0) THEN
	    M=-(COSRA*COSD-COSD0)/SIND0
	  ELSE
	    M=0
	  END IF
	END IF
C
	RETURN
C
C LMRD2
C
	ENTRY WNMCD2(RA0,DEC0,L,M,RA,DEC)
C
	SIND0=SIN(DEC0*DPI2)
	COSD=COS(DEC*DPI2)
	COSRA=COS((RA-RA0)*DPI2)
	M=M+2*COSRA*COSD/SIND0
C
	RETURN
C
C LMRD
C
	ENTRY WNMDLM(RA0,DEC0,LD,MD,RA,DEC)
C
	SIND0=SIN(DEC0*DPI2)
	COSD0=COS(DEC0*DPI2)
	DL=LD
	DM=MD
	D0=DM*DM*SIND0*SIND0+DL*DL-2*DM*COSD0*SIND0 !CORRECTION
	SIND=SQRT(ABS(SIND0*SIND0-D0))
	COSD=SQRT(ABS(COSD0*COSD0+D0))
	SIND=SIGN(SIND,SIND0)
	DEC=ATAN2(SIND,COSD)/DPI2
	IF (LD.NE.0) THEN
	  RA=WNGDPR(ATAN2(-DL,COSD0-DM*SIND0)+RA0*DPI2)/DPI2
	ELSE
	  RA=WNGDPR(ATAN2(1.D-10,COSD0-DM*SIND0)+RA0*DPI2)/DPI2
	END IF
C
	RETURN
C
C RDLM
C
	ENTRY WNMDRD(RA0,DEC0,LD,MD,RA,DEC)
C
	LD=-SIN((RA-RA0)*DPI2)*COS(DEC*DPI2)
	SIND0=SIN(DEC0*DPI2)
	IF (SIND0.NE.0) THEN
	  MD=-(COS((RA-RA0)*DPI2)*COS(DEC*DPI2)-COS(DEC0*DPI2))/
	1		SIN(DEC0*DPI2)
	ELSE
	  MD=0
	END IF
C
	RETURN
C
C RMDL
C
	ENTRY WNMDRM(RA0,DEC0,LD,MD,RA,DEC)
C
	COSD0=COS(DEC0*DPI2)
	SIND0=SIN(DEC0*DPI2)
	COSRA=COS((RA-RA0)*DPI2)
	SINRA=SIN((RA-RA0)*DPI2)
	DM=MD
	IF (COSRA.NE.0) THEN
	  DL=(DM*SIND0-COSD0)*SINRA/COSRA
	ELSE
	  DL=0
	END IF
	D0=DM*DM*SIND0*SIND0+DL*DL-2*DM*COSD0*SIND0 !CORRECTION
	SIND=SQRT(ABS(SIND0*SIND0-D0))
	COSD=SQRT(ABS(COSD0*COSD0+D0))
	SIND=SIGN(SIND,SIND0)
	DEC=ATAN2(SIND,COSD)/DPI2
	LD=DL
C
	RETURN
C
C DLRM
C
	ENTRY WNMDDL(RA0,DEC0,LD,MD,RA,DEC)
C
	SIND0=SIN(DEC0*DPI2)
	COSD0=COS(DEC0*DPI2)
	COSD=COS(DEC*DPI2)
	DL=LD
	IF (COSD.NE.0) THEN
	  SINRA=-DL/COSD
	ELSE
	  SINRA=0
	END IF
	IF (SINRA.GT.1.0) THEN
	  M=-100.
	  RA=-100.
	ELSE
	  COSRA=SQRT(ABS(1D0-SINRA*SINRA))
	  IF (SINRA.NE.0) THEN
	    RA=WNGDPR(ATAN2(SINRA,COSRA)+RA0*DPI2)/DPI2
	  ELSE
	    RA=WNGDPR(ATAN2(1.D-10,COSRA)+RA0*DPI2)/DPI2
	  END IF
	  IF (SIND0.NE.0) THEN
	    MD=-(COSRA*COSD-COSD0)/SIND0
	  ELSE
	    MD=0
	  END IF
	END IF
C
	RETURN
C
C
	END
