C+ WNPDOP.FOR
C  WNB 910624
C
C  Revisions:
C	WNB 920116	Typo in close
C
	LOGICAL FUNCTION WQDVOP(ID,NAM)
C
C  Open device
C
C  Result:
C
C	WQDVOP_L = WQDVOP( ID_J:IO, NAM_C*:I)
C				Open a plot device given by NAM, and return
C				the ID for the device
C	WQDVCL_L = WQDVCL( ID_J:IO)
C				Close the plot device given by ID. First
C				de-activate if necessary.
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'WQG_DEF'		!GENERAL AREA
	INCLUDE	'WQD_O_DEF'		!DEVICE AREA
C
C  Parameters:
C
C
C  Entry points:
C
	LOGICAL WQDVCL		!CLOSE DEVICE
C
C  Arguments:
C
	INTEGER ID		!PLOT ID
	CHARACTER*(*) NAM	!DEVICE NAME
C
C  Function references:
C
	LOGICAL WNGGVM		!GET MEMORY
	INTEGER WNGARA		!GET ADDRESS
	LOGICAL WQOPEN		!OPEN SYSTEM
	LOGICAL WNPCID		!CHECK ID
C
C  Data declarations:
C
	CHARACTER*(WQD_DEV_N) CNAM	!DEVICE NAME CHECK
C-
C
C INIT
C
	WQDVOP=.TRUE.					!ASSUME OK
	IF (WQG_STATE.LE.0) WQDVOP=WQOPEN()		!MAKE SURE SYSTEM OPEN
	IF (.NOT.WQDVOP) RETURN				!NO OPEN SYSTEM
C
C CHECK ID
C
	IF (WNPCID(ID)) THEN				!ALREADY OPEN
	  E_C=24
 20	  CONTINUE
	  WQDVOP=.FALSE.
	  RETURN
	END IF
	ID=0						!SET NOT OPEN
C
C FIND DEVICE
C
	J=WQG_DVLST					!START LIST
	DO WHILE (J.NE.0)
	  J=J-A_OB					!OFFSET
	  CALL WNGMTS(WQD_DEV_N,A_B(J+WQD_DEV_1),CNAM)	!GET DEVICE NAME
	  IF (NAM.EQ.CNAM) GOTO 10			!FOUND
	  J=A_J(J/LB_J+WQD_QUE_J)			!NEXT DEVICE
	END DO
	E_C=22						!UNKNOWN DEVICE
	GOTO 20
C
C GET AND FILL AREA
C
 10	CONTINUE
	J0=A_J(J/LB_J+WQD_LEN_J)			!LENGTH AREA
	IF (.NOT.WNGGVM(J0,J1)) THEN			!GET AREA
	  E_C=26
	  GOTO 20
	END IF
	CALL WNGMV(J0,A_B(J),A_B(J1-A_OB))		!FILL AREA
C
C OPEN DEVICE
C
	CALL WNPDEX(0,J1,0)				!OPEN DEVICE
C
C LINK OPEN DEVICE
C
	A_J((J1-A_OB)/LB_J+WQD_QUE_J)=WQG_QOP		!LINK DEVICE
	WQG_QOP=J1
	IF (WQG_STATE.LT.2) WQG_STATE=2			!SET AT LEAST ONE OPEN
	ID=J1						!RETURN AREA ID
C
	RETURN
C
C WQDVCL
C
	ENTRY WQDVCL(ID)
C
C INIT
C
	WQDVCL=.TRUE.					!ASSUME OK
	IF (WQG_STATE.LE.0) WQDVCL=WQOPEN()		!MAKE SURE SYSTEM OPEN
	IF (.NOT.WQDVCL) RETURN				!NO OPEN SYSTEM
C
C CHECK ID
C
	IF (.NOT.WNPCID(ID)) THEN			!NOT OPEN
	  E_C=25
	  WQDVCL=.FALSE.
	  RETURN
	END IF
C
C CLOSE DEVICE
C
	IF (A_J((ID-A_OB)/LB_J+WQD_ACT_J).NE.0) CALL WQDVDA(ID) !DEACTIVATE
	CALL WNPDEX(1,ID,0)				!CLOSE DEVICE
C
C DE-LINK
C
	J=WQG_QOP					!START LIST
	J1=WNGARA(WQG_QOP)				!ADDRESS START
	DO WHILE (J.NE.ID)
	  J1=J
	  J=A_J((J-A_OB)/LB_J+WQD_QUE_J)		!NEXT DEVICE
	END DO
	A_J((J1-A_OB)/LB_J)=A_J((J-A_OB)/LB_J+WQD_QUE_J) !UNLINK
	J0=A_J((J-A_OB)/LB_J+WQD_LEN_J)			!LENGTH
	CALL WNGFVM(J0,ID)				!FREE MEMORY
	ID=0						!SET CLOSED
	IF (WQG_QOP.EQ.0) WQG_STATE=1			!NO OPEN LEFT
C
	RETURN
C
C
	END
