C+ WNPEX0.FOR
C  WNB 911127
C
C  Revisions:
C
C  Extra routines WNP package
C
	SUBROUTINE WQ_DATE(ID,MSG)
C
C  Result:
C
C	CALL WQ_DATE( ID_J:I, MSG_C*:I)
C				Write time stamped message
C	CALL WQ_LINE( POS_E(0:1,0:1):I)
C				Draw simple line segment
C	CALL WQ_LINE_IX( POS_E(0:1,0:1):I, IX_J:I)
C				Draw simple line segment with index
C	CALL WQ_MARK( POS_E(0:1,0:0):I)
C				Draw single mark
C	CALL WQ_MARK_IX( POS_E(0:1,0:0):I, IX_J:I)
C				Draw single mark with index
C	CALL WQ_MLINE( N_J:I, POS1_E(0:1,N):I)
C				Draw marked line
C	CALL WQ_MLINE_IX( N_J:I, POS1_E(0:1,N):I, LIX_J:I, MIX_J:I)
C				Draw marked line with index
C	CALL WQ_RECT( POS_E(0:1,0:1):I)
C				Draw a rectangle from llhc to urhc
C	CALL WQ_RECT_IX( POS_E(0:1,0:1):I, IX_J:I)
C				Draw a rectangle from llhc to urhc with index
C	CALL WQ_SNTR(N_J:I, WIN_E(0:3):I, VIE_E(0:3):I)
C				Set WINdow and VIEwport for transfrom N
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'WQG_DEF'		!GENERAL AREA
	INCLUDE 'WQD_O_DEF'		!DEVICE AREA
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER ID			!DEVICE
	CHARACTER*(*) MSG		!STRING
	REAL POS(0:1,0:*)		!POSITION
	REAL POS1(0:1,0:*)		!POSITION
	INTEGER IX,LIX,MIX		!INDEX
	INTEGER N			!COUNT
	REAL WIN(0:3)			!WINDOW
	REAL VIE(0:3)			!VIEWPORT
C
C  Function references:
C
C
C  Data declarations:
C
	CHARACTER*24 TIM		!SYSTEM TIME
	CHARACTER*80 MSG2		!BUFFER TO SATISFY g77
	REAL LPOS(0:1,0:4)		!RECTANGLE POSITION
C-
C
C DATE
C
	CALL WNGSYT(TIM)				!GET TIME
	MSG2=MSG
	CALL WQMSG(ID,TIM(1:17)//'  '//MSG2)	!WRITE MESSAGE
C
	RETURN
C
C LINE
C
	ENTRY WQ_LINE(POS)
C
	GOTO 20
C
C LINE_IX
C
	ENTRY WQ_LINE_IX(POS,IX)
C
	CALL WQSPLI(IX)
 20	CONTINUE
	CALL WQPOLL(2,POS)
C
	RETURN
C
C MARK
C
	ENTRY WQ_MARK(POS)
C
	GOTO 30
C
C MARK_IX
C
	ENTRY WQ_MARK_IX(POS,IX)
C
	CALL WQSPMI(IX)
 30	CONTINUE
	CALL WQPOLM(2,POS)
C
	RETURN
C
C MLINE
C
	ENTRY WQ_MLINE(N,POS1)
C
	GOTO 40
C
C MLINE_IX
C
	ENTRY WQ_MLINE_IX(N,POS1,LIX,MIX)
C
	CALL WQSPLI(LIX)
	CALL WQSPMI(MIX)
 40	CONTINUE
	CALL WQPOLL(N,POS1)
	CALL WQPOLM(N,POS1)
C
	RETURN
C
C RECT
C
	ENTRY WQ_RECT(POS)
C
	GOTO 10
C
	RETURN
C
C RECT_IX
C
	ENTRY WQ_RECT_IX(POS,IX)
C
	CALL WQSPLI(IX)
 10	CONTINUE
	LPOS(0,0)=POS(0,0)
	LPOS(1,0)=POS(1,0)
	LPOS(0,1)=POS(0,1)
	LPOS(1,1)=POS(1,0)
	LPOS(0,2)=POS(0,1)
	LPOS(1,2)=POS(1,1)
	LPOS(0,3)=POS(0,0)
	LPOS(1,3)=POS(1,1)
	LPOS(0,4)=POS(0,0)
	LPOS(1,4)=POS(1,0)
	CALL WQPOLL(5,LPOS)
C
	RETURN
C
C SNTR
C
	ENTRY WQ_SNTR(N,WIN,VIE)
C
	CALL WQSWIN(N,WIN)
	CALL WQSVIE(N,VIE)
C
	RETURN
C
C
	END
