C+ WNPRTN_X.FOR
C  WNB 910624
C
C  Revisions:
C
C  General routines WNP package
C
	SUBROUTINE WNP_NTR0(NIN,IN,NOUT,OUT)
C
C  Result:
C
C	CALL WNP_NTR0( NIN_J:I , IN_E(0:1,*):I, NOUT_J:O, OUT_E(0:1,*):O)
C				Do normalized transform of list of N points
C				in IN to OUT
C	CALL WNP_DNTR0( NIN_J:I , IN_E(0:1,*):I, NOUT_J:O, OUT_E(0:1,*):O,
C					ID_J:I)
C				Do device transform of list of N points
C				in IN to OUT
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'WQG_DEF'		!GENERAL AREA
	INCLUDE 'WQD_O_DEF'		!DEVICE AREA
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER NIN			!NUMBER OF POINTS
	REAL IN(0:1,*)			!INPUT LIST
	INTEGER NOUT			!NUMBER OF POINTS
	REAL OUT(0:1,*)			!OUTPUT LIST
	INTEGER ID			!ID
C
C  Function references:
C
C
C  Data declarations:
C
C-
C
C NORMALIZED TRANSFORM NTR0
C
	DO I=1,NIN					!TRANSFORM POINTS
	  OUT(0,I)=WQG_NTR(0,0,WQG_CTR)*IN(0,I)+	!X
	1			WQG_NTR(1,0,WQG_CTR)
	  OUT(1,I)=WQG_NTR(2,0,WQG_CTR)*IN(1,I)+	!Y
	1			WQG_NTR(3,0,WQG_CTR)
	END DO
	NOUT=NIN
C
	RETURN
C
C DEVICE TRANSFORM DNTR0
C
	ENTRY WNP_DNTR0(NIN,IN,NOUT,OUT,ID)
C
	J=(ID-A_OB)/LB_E+WQD_NTR_E		!TRANSFORM POINTER
	DO I=1,NIN				!TRANSFORM POINTS
	  OUT(0,I)=A_E(J+0)*IN(0,I)+A_E(J+1)
	  OUT(1,I)=A_E(J+2)*IN(1,I)+A_E(J+3)
	END DO
	NOUT=NIN
C
	RETURN
C
C
	END
