C+ WNTIO6.FOR
C  WNB 930501
C
C  Revisions:
C
	SUBROUTINE WNTIO6(F,TP,LIN1,FENTJ,IENTJ,N)
C
C  Output a comment line attached to code
C
C  Result:
C
C	CALL WNTIO6( F_J(0:1):I, TP_J:I, LIN1_C*:I, FENTJ_J(0:*), IENTJ_J(0:*),
C			N_J:IO)
C				Output next comment line (initially N=0, used
C				as count) for current Format ENTry added to
C				code text in LIN1; using TP (0=Fortran, 1=C)
C				and file indicator F.
C	CALL WNTIO7( F_J(0:1):I, TP_J:I, LIN1_C*:I, FENTJ_J(0:*), IENTJ_J(0:*),
C			N_J:IO)
C				Output any remaining format lines for
C				current FENT (LIN1 not used)
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'WNT_O_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER F(0:1)			!FILE INDICATOR
	INTEGER TP			!FILE TYPE (FORTRAN/C)
	CHARACTER*(*) LIN1		!LINE OF CODE
	INTEGER FENTJ(0:*)		!FORMAT ENTRY
	INTEGER IENTJ(0:*)		!INPUT LINE ENTRY
	INTEGER N			!COMMENT LINE COUNT
C
C  Function references:
C
	INTEGER WNCALN			!STRING LENGTH
	INTEGER WNTIBR			!READ ENTRY
	LOGICAL WNTIO5			!GET COMMENT DATA
C
C  Data declarations:
C
	BYTE LCENTB(0:MXSLIN-1)		!COMMENT DATA
	  CHARACTER*(MXSLIN) LCENTC
	  EQUIVALENCE (LCENTB,LCENTC)
C-
C
C WNTIO6
C
	IF (WNTIO5(FENTJ,IENTJ,N,LCENTB,LCENTC)) THEN	!COMMENT PRESENT
	  IF (WNCALN(LIN1).GE.COMPOS-1) THEN
	    IF (TP.EQ.0) THEN				!FORTRAN
	      CALL WNCTXT(F(TP),'!AS !! !AS',
	1		LIN1,LCENTC)
	    ELSE					!C
	      CALL WNCTXT(F(TP),'!AS /* !AS */',
	1		LIN1,LCENTC)
	    END IF
	  ELSE
	    IF (TP.EQ.0) THEN				!FORTRAN
	      CALL WNCTXT(F(TP),'!AS!#C!! !AS',
	1		LIN1,COMPOS,LCENTC)
	    ELSE					!C
	      IF (LIN1(1:1).EQ.CHAR(9)) THEN
	        CALL WNCTXT(F(TP),'!AS!#C/* !AS */',
	1		LIN1,COMPOS,LCENTC)
	      ELSE
	        CALL WNCTXT(F(TP),'!AS!#C/* !AS */',
	1		LIN1,COMPOS+7,LCENTC)
	      END IF
	    END IF		
	  END IF
	ELSE						!NO COMMENT
	  CALL WNCTXT(F(TP),'!AS',LIN1)
	END IF
C
	RETURN
C
C WNTIO7
C
	ENTRY WNTIO7(F,TP,LIN1,FENTJ,IENTJ,N)
C
	DO WHILE (WNTIO5(FENTJ,IENTJ,N,LCENTB,LCENTC))	!MORE COMMENT LINES
	  IF (TP.EQ.0) THEN				!FORTRAN
	    CALL WNCTXT(F(TP),'!@!#C!! !AS',COMPOS,LCENTC)
	  ELSE						!C
	    CALL WNCTXT(F(TP),'!@!#C/* !AS */',COMPOS,LCENTC)
	  END IF
	END DO
C
	RETURN
C
C
	END
