	BLOCK DATA DWARF_BLOCK
C	Created by BLDDEF from: _$1$DIA3:[TESTDWARF.SRC.DEF]DWARF.DEF; on 17-OCT-90
C	HjV 921208	Removed all equivalence and add names to common block
C       AXC 010709	linux port - data initialisation
C
C
C
	INTEGER*4 DWARF$LENGTH
	INTEGER*4 DWARF$TYPE
	INTEGER*4 DWARF$BELL
	INTEGER*4 DWARF$MSGDEV
	INTEGER*4 DWARF$LEVEL
	INTEGER*4 DWARF$IOBFSZ
	INTEGER*4 DWARF$TAPEBLSZ
	INTEGER*4 DWARF$EXTENDSZ
	INTEGER*4 DWARF$LENSTR
	INTEGER*4 DWARF$ASK
	INTEGER*4 DWARF$SAVELAST
	INTEGER*4 DWARF$TEST
	INTEGER*4 DWARF$LENNODE
	INTEGER*4 DWARF$CURNODE(1)
	CHARACTER*80 DWARF$CURNODE_C
	INTEGER*4 DWARF$LOGLEVEL
	INTEGER*4 DWARF$LOGFATAL
	INTEGER*4 DWARF$STREAM(1)
	CHARACTER*12 DWARF$STREAM_C
	INTEGER*4 DWARF$LENID
	INTEGER*4 DWARF$IDENT(1)
	CHARACTER*4 DWARF$IDENT_C
	INTEGER*4 DWARF$IBMODE
C
	COMMON /DWARF_COMMON/ DWARF$LENGTH, DWARF$TYPE, DWARF$BELL,
     *		DWARF$MSGDEV, DWARF$LEVEL, DWARF$IOBFSZ, DWARF$TAPEBLSZ,
     *		DWARF$EXTENDSZ, DWARF$LENSTR, DWARF$ASK, DWARF$SAVELAST,
     *		DWARF$TEST, DWARF$LENNODE, DWARF$CURNODE_C,
     *		DWARF$LOGLEVEL, DWARF$LOGFATAL, DWARF$STREAM_C,
     *		DWARF$LENID, DWARF$IDENT_C, DWARF$IBMODE
C
C
	DATA DWARF$BELL /0/
	DATA DWARF$MSGDEV /0/
	DATA DWARF$LEVEL /2/
	DATA DWARF$IOBFSZ /32768/
	DATA DWARF$TAPEBLSZ /16384/
	DATA DWARF$EXTENDSZ /64/
	DATA DWARF$LENSTR /2/
	DATA DWARF$ASK /0/
	DATA DWARF$SAVELAST /0/
	DATA DWARF$TEST /0/
	DATA DWARF$LENNODE /1/
	DATA DWARF$CURNODE_C /'0'/
	DATA DWARF$LOGLEVEL /8/
	DATA DWARF$LOGFATAL /0/
	DATA DWARF$STREAM_C /'$1'/
	DATA DWARF$LENID /0/
	DATA DWARF$IDENT_C /'XYZ'/
	DATA DWARF$IBMODE /0/
	END











