C+ NCLEAN.FOR
C  WNB 910809
C
C  Revisions:
C	WNB 910828	Add RUN
C	WNB 921202	Add DATA clean
C	CMV 960122	Warning if /NORUN ignored
C
	SUBROUTINE NCLEAN
C
C  Main routine to clean Map files
C
C  Result:
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NCL_DEF'
	INCLUDE 'MPH_O_DEF'		!MAP HEADER
C
C  Parameters:
C
C
C  Arguments:
C
C
C  Function references:
C
	LOGICAL NMASTG			!GET A MAP
	LOGICAL WNDRUN			!TEST RUN
C
C  Data declarations:
C
	INTEGER MPHP			!MAP POINTER
	BYTE MPH(0:MPHHDL-1)		!MAP HEADER
	  INTEGER MPHJ(0:MPHHDL/4-1)
	  EQUIVALENCE (MPH,MPHJ)
	INTEGER APHP			!AP POINTER
	BYTE APH(0:MPHHDL-1)		!AP HEADER
	  INTEGER APHJ(0:MPHHDL/4-1)
	  EQUIVALENCE (APH,APHJ)
C-
C
C PRELIMINARIES
C
	CALL NCLINI				!INIT PROGRAM
	IF (.NOT.WNDRUN()) 
	1	CALL WNCTXT(F_TP,'Ignored option /NORUN')
C
C DISTRIBUTE
C
 10	CONTINUE
	CALL NCLDAT				!GET USER DATA
	IF (OPT.EQ.'HIS') THEN			!MAKE HISTOGRAM
	  IF (.NOT.WNDRUN()) CALL WNGEX		!NO RUN
	  DO WHILE (NMASTG(FCAMAP,MSETS,MPH,MPHP,MAPNAM)) !ALL SETS
	    CALL WNDSTI(FCAMAP,MAPNAM)		!MAKE INDEX
	    IF (MAPNAM(4).EQ.0) THEN		!MAP
	      CALL NCLHIS(MPHP,0)
	    ELSE IF (MAPNAM(4).EQ.1) THEN	!AP
	      DO I=0,7
		APNAM(I)=MAPNAM(I)		!SET NAME
	      END DO
	      NODAP=NODMAP			!NODE NAME
	      CALL NCLHIS(0,MPHP)
	    END IF
	  END DO
	  CALL WNFCL(FCAMAP)			!CLOSE INPUT
	ELSE IF (OPT.EQ.'BEA') THEN		!HOGBOM CLEAN
	  IF (.NOT.WNDRUN()) CALL WNGEX		!NO RUN
	  IF (NMASTG(FCAMAP,MSETS,MPH,MPHP,MAPNAM)) THEN !GET MAP
	    CALL WNDSTI(FCAMAP,MAPNAM)		!MAKE INDEX
	    IF (NMASTG(FCAMAP,ASETS,APH,APHP,APNAM)) THEN !GET AP
	      CALL WNDSTI(FCAMAP,APNAM)		!MAKE INDEX
	      CALL NCLBEA(MPH,APH)		!DO CLEAN
	    END IF
	  END IF
	  CALL WNFCL(FCAMAP)			!CLOSE FILE
	ELSE IF (OPT.EQ.'UVC') THEN		!CLARK CLEAN
	  IF (.NOT.WNDRUN()) CALL WNGEX		!NO RUN
	  IF (NMASTG(FCAMAP,MSETS,MPH,MPHP,MAPNAM)) THEN !GET MAP
	    CALL WNDSTI(FCAMAP,MAPNAM)		!MAKE INDEX
	    IF (NMASTG(FCAMAP,ASETS,APH,APHP,APNAM)) THEN !GET AP
	      CALL WNDSTI(FCAMAP,APNAM)		!MAKE INDEX
	      CALL NCLUV(MPHP,APHP)		!DO CLEAN
	    END IF
	  END IF
	  CALL WNFCL(FCAMAP)			!CLOSE FILE
	ELSE IF (OPT.EQ.'DAT') THEN		!DATA CLEAN
	  IF (.NOT.WNDRUN()) CALL WNGEX		!NO RUN
	  IF (NMASTG(FCAMAP,MSETS,MPH,MPHP,MAPNAM)) THEN !GET MAP
	    CALL WNDSTI(FCAMAP,MAPNAM)		!MAKE INDEX
	    IF (NMASTG(FCAMAP,ASETS,APH,APHP,APNAM)) THEN !GET AP
	      CALL WNDSTI(FCAMAP,APNAM)		!MAKE INDEX
	      CALL NCLCDT(MPHP,APHP)		!DO CLEAN
	    END IF
	  END IF
	  CALL WNFCL(FCAMAP)			!CLOSE FILE
	ELSE IF (OPT.EQ.'COM') THEN		!CLARK CLEAN COMPONENT LIST
	  IF (.NOT.WNDRUN()) CALL WNGEX		!NO RUN
	  IF (NMASTG(FCAMAP,MSETS,MPH,MPHP,MAPNAM)) THEN !GET MAP
	    CALL WNDSTI(FCAMAP,MAPNAM)		!MAKE INDEX
	    IF (NMASTG(FCAMAP,ASETS,APH,APHP,APNAM)) THEN !GET AP
	      CALL WNDSTI(FCAMAP,APNAM)		!MAKE INDEX
	      CALL NCLCMP(MPHP,APHP)		!DO CLEAN
	    END IF
	  END IF
	  CALL WNFCL(FCAMAP)			!CLOSE FILE
	ELSE IF (OPT.EQ.'URE') THEN		!CLARK CLEAN
	  IF (.NOT.WNDRUN()) CALL WNGEX		!NO RUN
	  IF (NMASTG(FCAMAP,MSETS,MPH,MPHP,MAPNAM)) THEN !GET MAP
	    CALL WNDSTI(FCAMAP,MAPNAM)		!MAKE INDEX
	    CALL NCLUV(MPHP,0)			!DO CLEAN
	  END IF
	  CALL WNFCL(FCAMAP)			!CLOSE FILE
	END IF
C
	RETURN					!READY
C
C
	END
