C+ NMANVS.FOR
C  WNB 910327
C
C  Revisions:
C	HjV 930311	Change some text
C
	SUBROUTINE NMANVS
C
C  Convert WMP file to newest format
C
C  Result:
C
C	CALL NMANVS	will convert a WMP file to newest version
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NMA_DEF'
	INCLUDE 'MPH_O_DEF'		!SET HEADER
C
C  Parameters:
C
C
C  Arguments:
C
C
C  Function references:
C
	LOGICAL WNFRD			!READ DATA
	LOGICAL WNFWR			!WRITE DATA
	LOGICAL NMASTH			!GET A SET WITH NO VERSION CHECK
C
C  Data declarations:
C
	INTEGER SET(0:7,0:1)		!ALL SETS
	INTEGER MPHP			!SET HEADER POINTER
	INTEGER SNAM(0:7)		!SET NAME
	BYTE MPH(0:MPHHDL-1)		!SET HEADER
	  INTEGER*2 MPHI(0:MPHHDL/2-1)
	  INTEGER MPHJ(0:MPHHDL/4-1)
	  REAL MPHE(0:MPHHDL/4-1)
	  EQUIVALENCE (MPH,MPHI,MPHJ,MPHE)
C-
C
C INIT
C
	DO I=0,7				!SET SET *.*.*.*.*.*.*
	  DO I1=0,1
	    SET(I,I1)=0
	  END DO
	END DO
	SET(0,0)=1				!1 LINE
	DO I=0,7
	  SET(I,1)=-1				!*
	END DO
C
C DO ALL SETS
C
	DO WHILE (NMASTH(FCAOUT,SET,MPH,MPHP,SNAM))	!GET SET
C
C MAKE FROM VERSION 1
C
	  IF (MPHI(MPH_VER_I).EQ.1) THEN		!STILL VERSION 1
	    MPHI(MPH_LEN_I)=MPHHDL			!NEW LENGTH
	    MPHI(MPH_VER_I)=MPHHDV			!NEW VERSION
	  END IF					!VERSION 1
C
C FINISH
C
	  IF (.NOT.WNFWR(FCAOUT,MPHHDL,MPH(0),MPHP)) THEN !REWRITE SET HEADER
10	    CONTINUE
	    CALL WNCTXT(F_TP,'!/Error rewriting Map Set(s)')
	    GOTO 900
	  END IF
	END DO
C
C READY
C
 800	CONTINUE
	CALL WNFCL(FCAOUT)				!CLOSE FILE
C
	RETURN
C
C ERROR
C
 900	CONTINUE
	CALL WNFCL(FCAOUT)				!CLOSE FILE
	RETURN						!READY
C
C
	END
