C+ NMARFS.FOR
C  CMV 940929
C
C  Revisions:
C	CMV 940929	Created
C
	SUBROUTINE NMARFS(OUT,IN)
C
C  Convert FITS string
C
C  Result:
C
C	CALL NMAWFS( OUT_C(*), IN_C(*) )
C		Copies FITS String in header record IN to OUT
C
C  PIN references:
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'MPH_O_DEF'		!MAP HEADER
C
C  Parameters:
C
C
C  Arguments:
C
	CHARACTER*(*) IN		!INPUT FITS HEADER RECORD
	CHARACTER*(*) OUT		!OUTPUT STRING
C
	OUT=' '				!DEFAULT TO BLANK
	I1=10
	DO WHILE (IN(I1:I1).EQ.' '.AND.I1.LT.LEN(IN)) 	!SKIP SPACES
	   I1=I1+1
	END DO
C
	IF (IN(I1:I1).EQ.'''') THEN			!QUOTED STRING
	   I1=I1+1
	   I2=I1
	   DO WHILE (IN(I2:I2).NE.''''.AND.I2.LE.LEN(IN)) !FIND END
	      I2=I2+1
	   END DO
	   OUT=IN(I1:I2-1)				!COPY
	ELSE IF (I1.LT.LEN(IN)) THEN			!UNQUOTED STRING
	   OUT=IN(I1:)					!COPY 
	END IF
C
	RETURN
	END
