!+ SMP.DSC
!  WNB 930929
!
!  Revisions:
!
%REVISION=WNB=930929="Original version"
!
!	Define R-series map header
!
%COMMENT="SMP.DSC defines the R-series map header block"
%COMMENT=" "
!
%VERSION=1					!VERSION
%SYSTEM=1
%USER=WNB
%%DATE
%%NAME
!
%LOCAL=QSMPL=512				!REQUIRED LENGTH
%LOCAL=QFNM=64					!OFFSET TO FILE NAME REQUIRED
!-
.PARAMETER
.BEGIN=SMP
	ID	C4		!IDENTIFICATION (E.G. '.SMP')
	LEN	I		!LENGTH HEADER
	CRD	C11		!CREATION DATE (DD-MMM-YYYY)
	CRT	C5		!CREATION TIME (HH:MM)
	RVD	C11		!REVISION DATE (DD-MMM-YYYY)
	RVT	C5		!REVISION TIME (HH:MM)
	RVN	I		!REVISION COUNT
	VER	I		!VERSION
	-	-(0:1)		!RESERVED
	MLH	J		!LINK TO MAP
  .OFF=QFNM			!RESERVED
	FNM	C12		!FIELD NAME
	EPO	E		!EPOCH (E.G. 1950.0)
	RA	D		!RIGHT ASCENSION (CIRCLES)
	DEC	D		!DECLINATION (CIRCLES)
	FRQ	D		!FREQUENCY (MHZ)
	BDW	D		!BANDWIDTH (MHZ)
	RAO	D		!OBSERVED RIGHT ASCENSION (CIR)
	DCO	D		!OBSERVED DECL. (CIRCLES)
	FRO	D		!OBSERVED FREQ. (CIRCLES)
	ODY	I		!OBSERVED DAY SINCE JAN 0
	OYR	I		!OBSERVED YEAR OR 0 (E.G. 1985)
	DCD	I		!DATA CODE:	2=I2
				!		4=I4
				!		5=R4
				!		8=R8
	PCD	I		!PROGRAM CODE:	0=RMAP
	SRA	D		!SEPARATION IN RA (CIRCLES)
	SDC	D		!SEPARATION DEC (CIRCLES)
	SFR	D		!SEPARATION FREQ. (MHZ)
	NRA	I		!# OF POINTS IN RA
	NDC	I		!# OF POINTS IN DEC
	NFR	I		!# OF POINTS IN FREQ.
	ZRA	I		!CENTRE RA (1ST POINT=0)
	ZDC	I		!CENTRE DEC (1ST LINE=0)
	ZFR	I		!CENTRE FREQUENCY (1ST MAP=0)
	MXR	I		!POSITION MAX. IN RA
	MXD	I		!POSITION MAX. IN DEC
	MXF	I		!POSITION MAX. IN FREQUENCY
	MNR	I		!POS. MIN. RA
	MND	I		!POS. MIN. DEC
	MNF	I		!POS. MIN. FREQ.
	MAX	E		!MAX. IN MAPS
	MIN	E		!MIN. IN MAPS
	SHR	D		!SHIFT IN RA (ADD, CIRCLES)
	SHD	D		!SHIFT IN DEC (ADD, CIRCLES)
	SHF	D		!SHIFT IN FREQ. (ADD, MHZ)
	SUM	D		!NORMALISING SUM (?ALL MAPS?)
	UNI	E		!MULTIPLIER TO GET JY
	UCM	C24		!USER COMMENT
	NPT	J		!# OF INPUT DATA POINTS
	NBS	I		!# OF INPUT BASELINES
	NST	I		!# OF INPUT SETS (=MEASUREM.)
	TYP	C4		!MAP TYPE (MAP, AP, COV ETC)
	POL	C2		!POL. TYPE (OR SO)
	CD	I(0:7)		!0: TAPER TYPE
				!1: CONVOLUTION TYPE
				!2: CORRECT FOR CONVOLUTION
				!3: CLIPPING DONE
				!4: SOURCE SUBTRACTION
				!5: DATA TYPE
				!6: UV COORDINATE TYPE
	EPT	I		!MAP EPOCH USED:
				!0: APPARENT
				!1: AS SPECIFIED IN EPOCH
	OEP	E		!OBSERVATION EPOCH (EG 1985.78)
	NOS	E		!MAP NOISE
	FRA	E		!FIELD SIZE RA (CIRCLES)
	FDC 	E		!FIELD SIZE DEC (CIRCLES)
	FFR	E		!FIELD SIZE FREQ (MHZ)
	TEL	C8		!NAME OF TELESCOPE
	FSR	I		!FFT SIZE VERSION 3 RA
	FSD	I		!FFT SIZE VERSION 3 DEC
	-	-(0:3)
!			NEXT 5 SPECIAL OH INFO FOR GRONINGEN
	GBD	E		!BAND
	GVL	E		!VLCTY
	GFR	I		!FREQC
	GNF	I		!NRFREQ
	GVC	I		!VELC
	-	-(0:1)		!FILL
	CFR	D		!AVERAGE CORRECTED FREQUENCY
  .OFF=QSMPL
.END
!-
