C+ NGCALC.FOR
C  WNB 920818
C
C  Revisions:
C	WNB 920902	Add TRANSpose
C	CMV 940805	Add BASEline
C
	SUBROUTINE NGCALC
C
C  Main program for plotting NGC files
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NGC_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
C
C  Function references:
C
	INTEGER NGCNOD			!GET NGC NODE
C
C  Data declarations:
C
C-
C
C PRELIMINARIES
C
	CALL NGCINI				!INIT PROGRAM
C
C DISTRIBUTE
C
 10	CONTINUE
	CALL NGCDAT				!GET DATA
	IF (OPT.EQ.'QUI') THEN			!EXIT
	  CALL WNFCL(FCAOUT)			!CLOSE DATA
	  RETURN				!EXIT
	ELSE IF (OPT.EQ.'NOD') THEN		!SWITCH NODE
	  CALL WNFCL(FCAOUT)			!CLOSE CURRENT NODE
	ELSE IF (OPT.EQ.'SHO') THEN		!SHOW
	  CALL NGCPRT
	ELSE IF (OPT.EQ.'BRI') THEN		!SHOW BRIEF
	  CALL NGCPBR
	ELSE IF (OPT.EQ.'DEL') THEN		!DELETE
 12	  CONTINUE
	  CALL WNCTXT(3,'!/Option not yet implemented!/')
	ELSE IF (OPT.EQ.'COM') THEN		!COMBINE
	  CALL NGCCOB
	ELSE IF (OPT.EQ.'MER') THEN		!MERGE
	  CALL NGCCOB
	ELSE IF (OPT.EQ.'TRA') THEN		!TRANSPOSE
	  CALL NGCTRP
	ELSE IF (OPT.EQ.'BAS') THEN		!BASELINE TRANSPOSE
	  CALL NGCBAS
	ELSE IF (OPT.EQ.'CAL') THEN		!CALCULATE
	  CALL NGCCAL
	ELSE IF (OPT.EQ.'EXT') THEN		!EXTRACT
	  CALL NGCEXT
	ELSE IF (OPT.EQ.'COP') THEN		!COPY
	  CALL NGCCOP
	ELSE IF (OPT.EQ.'MON') THEN		!MONGO
	  CALL NGCMON
	ELSE IF (OPT.EQ.'PLO') THEN		!PLOT
	  CALL NGCPLT
	ELSE IF (OPT.EQ.'NVS') THEN
	  CALL NGCNVS				!NEW VERSION
	ELSE IF (OPT.EQ.'CVX') THEN
	  CALL NGCXCV				!MACHINE FORMAT CONVERSION
	END IF
C
	GOTO 10					!CYCLE
C
C
	END
