C+ NPLDHA.FOR
C  HjV 940117
C
C  Revisions:
C       HjV 940329   Fill in dummy arguments in call to NPLTEL and NPLRES
C
	SUBROUTINE NPLDHA (LDATTP,IPOL,NHV)
C
C  Load data in buffer as (CHAN, IFR)
C
C  Result:
C
C	CALL NPLDHA		Load data in buffer as (CHAN, IFR)
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'STH_O_DEF'		!SET HEADER
	INCLUDE 'NPL_DEF'
C
C  Parameters:
C
	INTEGER LDATTP			!CURRENT DATA TYPE
	INTEGER IPOL
	INTEGER NHV(0:1)		!# OF PAGES
C
C  Arguments:
C
C
C  Function references:
C
	LOGICAL NSCSIF			!READ IFR TABLE
	LOGICAL NSCSTL			!GET A SET
C
C  Data declarations:
C
	INTEGER NPLOT			!# OF INTERFEROMETERS TO DO
	INTEGER PTXT(MXNCHN)		!CROSS CHANNELS
	INTEGER SCHAN(0:MXNCHN-1)	!CHANNELS TO DO
	INTEGER TABIFR(0:STHTEL-1,0:STHTEL-1) !IFR PLOT POINTERS
	INTEGER BTEL(0:1,0:STHIFR-1)	!TEL. TO PLOT
	INTEGER*2 IFRT(0:STHIFR-1)	!IFR TABLE
	INTEGER IFRA(0:1,0:STHIFR-1)
	REAL ANG(0:2,0:STHIFR-1)
	REAL BASEL(0:STHIFR-1)		!BASELINES
	INTEGER IRED(0:STHIFR-1)	!REDUNDANT INDICATORS
	INTEGER STHP			!SET HEADER POINTER
	BYTE STH(0:STH__L-1)		!SET HEADER
	  INTEGER*2 STHI(0:STH__L/LB_I-1)
	  INTEGER STHJ(0:STH__L/LB_J-1)
	  REAL STHE(0:STH__L/LB_E-1)
	  DOUBLE PRECISION STHD(0:STH__L/LB_D-1)
	  EQUIVALENCE (STH,STHI,STHJ,STHE,STHD)
C-
C
C FIND REDUNDANT INTERFEROMETERS
C
	CALL WNGMVZ(STH__L,STH(0))			!MAKE SURE PROPER NUMBERS
	IF (NSCSTL(FCAIN,SETS,STH(0),STHP,SETNAM,LPOFF)) THEN !A SET
	  CALL WNDSTR(FCAIN,SETS)			!RESET SET SEARCH
	  IF (OPT.EQ.'RES' .AND. NSRC(0).EQ.0) THEN     !REDUNDANCY ASKED
	    IF (.NOT.NSCSIF(FCAIN,STH,IFRT,IFRA,ANG)) THEN	!READ IFR TABLE
	      CALL WNCTXT(F_TP,'Read error IFR table')
	      RETURN
	    END IF
	    CALL NSCMBL(STHE(STH_RTP_E),STHJ(STH_NIFR_J),IFRT,
	1		SIFRS,BASEL)			!MAKE BASELINES
	    CALL NCARRT(STHJ(STH_NIFR_J),BASEL,1E0,IRED,ANG) !GET REDUNDANT
	    DO I1=0,STHJ(STH_NIFR_J)-1			!DELETE NON-REDUNDANT
	      IF (IRED(I1).LE.0) THEN			!NON-REDUNDANT
		SIFRS(IFRA(0,I1),IFRA(1,I1))=.FALSE.
		SIFRS(IFRA(1,I1),IFRA(0,I1))=.FALSE.
	      END IF
	    END DO
	  END IF
	END IF
C
C  FIND CHANNELS TO DO
C
	NPLOT=0						!SELECTED CIFRS
	DO I=0,MXNCHN-1 				!SET NOT CHANNEL
	  SCHAN(I)=-1
	END DO
	DO WHILE(NSCSTL(FCAIN,SETS,STH(0),STHP,SETNAM,LPOFF)) !ALL SETS
	  CALL WNDSTI(FCAIN,SETNAM)			!MAKE SURE OF NAME
	  IF (SETNAM(3).LT.MXNCHN) THEN 		!CAN DO
	    IF (SCHAN(SETNAM(3)).LT.0) THEN		!NEW ONE
	      SCHAN(SETNAM(3))=1			!SET CHANNEL SELECTED
	      NPLOT=NPLOT+1
	    END IF
	  END IF
	END DO
	I1=0
	DO I=0,MXNCHN-1		        		!SET ORDER
	  IF (SCHAN(I).GT.0) THEN
	    SCHAN(I)=I1	        			!SET ORDER
	    I1=I1+1
	    PTXT(I1)=I  				!SAVE CHANNEL NUMBER
	  END IF
	END DO
C
C  FIND TELESCOPE/INTERFEROMETERS TO DO
C
	NPLOT=0						!SELECTED CIFRS
 	IF (OPT.EQ.'TEL') THEN                          !FIND TELESCOPES TO DO
	  DO I1=1,STHTEL				!ANNOTATION
	    IF (STELS(I1-1)) THEN
	      NPLOT=NPLOT+1				!SELECTED
	      TXT(1)(NPLOT:NPLOT)=TELNAM(I1:I1)
	    END IF
	  END DO
	ELSE                                            !FIND INTERF. to DO
	  DO I=0,STHTEL-1
	    DO I1=I,STHTEL-1				!ANNOTATION
	      TABIFR(I,I1)=-1				!SET NOT SELECTED
	      IF (SIFRS(I,I1)) THEN			!SELECTED
	        BTEL(0,NPLOT)=I                   	!SAVE TEL. TO PLOT
	        BTEL(1,NPLOT)=I1
		BASEL(NPLOT)=ABS(STHE(STH_RTP_E+I)-STHE(STH_RTP_E+I1))
		NPLOT=NPLOT+1
	      END IF
	    END DO
	  END DO
	  IF (IFR_MODE.EQ.'SORT') THEN 			!SORT ON BASELINE
	    DO I=0,NPLOT-2
	      DO I1=0,NPLOT-2-I
	        IF (ABS(BASEL(I1)-BASEL(I1+1)).GT.1 .AND.
	1	        BASEL(I1).GT.BASEL(I1+1)) THEN    !SWAP
		  R0=BASEL(I1)
		  BASEL(I1)=BASEL(I1+1)
		  BASEL(I1+1)=R0
		  DO I2=0,1
		    I3=BTEL(I2,I1)
		    BTEL(I2,I1)=BTEL(I2,I1+1)
		    BTEL(I2,I1+1)=I3
		  END DO
	        END IF
	      END DO
	    END DO
	  END IF
	  DO I=0,NPLOT-1                  		!SET IFR NAMES
	    TXT(1)(I+1:I+1)=TELNAM(BTEL(0,I)+1:BTEL(0,I)+1)
	    TXT(2)(I+1:I+1)=TELNAM(BTEL(1,I)+1:BTEL(1,I)+1)
	    TABIFR(BTEL(0,I),BTEL(1,I))=I         	!SET IFR PTR
	  END DO
	END IF
C
C PLOT TELESCOPE/RESIDUALS ERRORS
C
 	IF (OPT.EQ.'TEL') THEN                          !FIND TELESCOPES TO DO
	   CALL NPLTEL (LDATTP,IPOL,NPLOT,PTXT,NHV,TABIFR,SCHAN,I1)
	ELSE			                        !FIND REDUNDANT INTERF.
	   CALL NPLRES (LDATTP,IPOL,NPLOT,PTXT,NHV,TABIFR,SCHAN,I1)
	ENDIF
C
C
	END

