	BLOCK DATA BLDPPD_BLOCK
C	Created by BLDDEF from: _$1$DIA3:[TESTDWARF.SRC.DEF]BLDPPD.DEF; on 17-OCT-90
C	HjV 921208	Removed all equivalence and add names to common block
C       AXC 010907      LinuxPort - data initialisation
C
	INTEGER*4 BPD$LENGTH
	INTEGER*4 BPD$TYPE
	INTEGER*4 BPD$REFNR
	CHARACTER*16 BPD$REFNAM(64)
	INTEGER*4 BPD$INDEX(6)
	INTEGER*4 BPD$PARM(6)
	INTEGER*4 BPD$PROT(6)
	INTEGER*4 BPD$HELP(6)
C
	COMMON /BLDPPD/ BPD$REFNR, BPD$REFNAM, BPD$INDEX, BPD$PARM,
     *			BPD$PROT,  BPD$HELP
C
C
	DATA BPD$REFNR /0/
	DATA BPD$INDEX /2048,5*0/
	DATA BPD$PARM /4096,5*0/
	DATA BPD$PROT /4096,5*0/
	DATA BPD$HELP /2048,5*0/

	END
