	BLOCK DATA CLI_BLOCK
C	Created by BLDDEF from: USER5:[OLNON.SYS]CLI.DEF; on 13-SEP-91
C	HjV 921208	Removed all equivalence and add names to common block
C
C
C
	INTEGER*4 CLI$LENGTH
	INTEGER*4 CLI$TYPE
	INTEGER*4 CLI$NRARG
	DATA CLI$NRARG /0/
	INTEGER*4 CLI$NRPAR
	DATA CLI$NRPAR /0/
	INTEGER*4 CLI$NREXP
	DATA CLI$NREXP /0/
	INTEGER*4 CLI$NRQUA
	DATA CLI$NRQUA /0/
	CHARACTER*16 CLI$NAME(20)
	DATA CLI$NAME /20*' '/
	INTEGER*4 CLI$ATTR(20)
	DATA CLI$ATTR /20*0/
	INTEGER*4 CLI$STAT(20)
	DATA CLI$STAT /20*0/
	INTEGER*4 CLI$IDPRO(20)
	DATA CLI$IDPRO /20*0/
	INTEGER*4 CLI$IDDEF(20)
	DATA CLI$IDDEF /20*0/
	INTEGER*4 CLI$IDVAL(20)
	DATA CLI$IDVAL /20*0/
C
	COMMON /CLI_COMMON/ CLI$LENGTH, CLI$TYPE, CLI$NRARG, CLI$NRPAR,
     *		CLI$NREXP, CLI$NRQUA, CLI$NAME,  CLI$ATTR,
     *		CLI$STAT,  CLI$IDPRO, CLI$IDDEF, CLI$IDVAL
C
C
	END
