	BLOCK DATA PARM_BLOCK
C	Created by BLDDEF from: _$1$DIA3:[TESTDWARF.SRC.DEF]PARM.DEF; on 17-OCT-90
C	HjV 921208	Removed all equivalence and add names to common block
C	AXC 010709	linux-port -data init
C
C
C
	INTEGER*4 PARM$LENGTH
	INTEGER*4 PARM$TYPE
	CHARACTER*12 PARM$PROGNAM
	INTEGER*4 PARM$LP
	CHARACTER*12 PARM$STREAM
	INTEGER*4 PARM$LS
	CHARACTER*25 PARM$PROGSTRM
	INTEGER*4 PARM$LPS
	INTEGER*4 PARM$MODE
	INTEGER*4 PARM$PRC
	INTEGER*4 PARM$DEV
	INTEGER*4 PARM$SYSOUT
	INTEGER*4 PARM$EXH(1)
	INTEGER*4 PARM$EHLINK
	INTEGER*4 PARM$EHADDR
	INTEGER*4 PARM$EHNRARG
	INTEGER*4 PARM$EHSTADDR
	INTEGER*4 PARM$EHSTATUS
	INTEGER*4 PARM$NRKEY
	INTEGER*4 PARM$KEYLDYN
	INTEGER*4 PARM$KEYADYN
	INTEGER*4 PARM$KEYACUR
	INTEGER*4 PARM$KEYPART(1)
	CHARACTER*16 PARM$KEY
	CHARACTER*16 PARM$PKEY
	INTEGER*4 PARM$LK
	INTEGER*4 PARM$LKMIN
	INTEGER*4 PARM$APPD
	INTEGER*4 PARM$LOOP
	INTEGER*4 PARM$ASK
	INTEGER*4 PARM$IO
	INTEGER*4 PARM$ASKSW
	INTEGER*4 PARM$EXELDYN
	INTEGER*4 PARM$EXEADYN
	INTEGER*4 PARM$EXEAVAL
	INTEGER*4 PARM$EXEASW
	INTEGER*4 PARM$EXENRS
	INTEGER*4 PARM$EXEVPS
	INTEGER*4 PARM$EXETYPE
	INTEGER*4 PARM$DEFLDYN
	INTEGER*4 PARM$DEFADYN
	INTEGER*4 PARM$DEFAVAL
	INTEGER*4 PARM$DEFASW
	INTEGER*4 PARM$DEFNRS
	INTEGER*4 PARM$DEFVPS
	INTEGER*4 PARM$DEFSNR
	INTEGER*4 PARM$DEFPTR
	INTEGER*4 PARM$DEFCNT
	INTEGER*4 PARM$DEFLDEF
	INTEGER*4 PARM$DEFADEF
	INTEGER*4 PARM$VALLDYN
	INTEGER*4 PARM$VALADYN
	INTEGER*4 PARM$VALAVAL
	INTEGER*4 PARM$VALASW
	INTEGER*4 PARM$VALNRS
	INTEGER*4 PARM$VALVPS
	INTEGER*4 PARM$VALSNR
	INTEGER*4 PARM$VALPTR
	INTEGER*4 PARM$VALCNT
	INTEGER*4 PARM$SAVLEN
	INTEGER*4 PARM$SAVADR
	INTEGER*4 PARM$KEYEND
C
	COMMON /PARM_COMMON/ PARM$LENGTH, PARM$TYPE, PARM$PROGNAM,
     *		PARM$LP, PARM$STREAM, PARM$LS, PARM$PROGSTRM, PARM$LPS,
     *		PARM$MODE, PARM$PRC, PARM$DEV, PARM$SYSOUT, PARM$EHLINK,
     *		PARM$EHADDR, PARM$EHNRARG, PARM$EHSTADDR, PARM$EHSTATUS,
     *		PARM$NRKEY, PARM$KEYLDYN, PARM$KEYADYN, PARM$KEYACUR,
     *		PARM$KEY, PARM$PKEY, PARM$LK, PARM$LKMIN,
     *		PARM$APPD, PARM$LOOP, PARM$ASK, PARM$IO, PARM$ASKSW,
     *		PARM$EXELDYN, PARM$EXEADYN, PARM$EXEAVAL, PARM$EXEASW,
     *		PARM$EXENRS, PARM$EXEVPS, PARM$EXETYPE, PARM$DEFLDYN,
     *		PARM$DEFADYN, PARM$DEFAVAL, PARM$DEFASW, PARM$DEFNRS,
     *		PARM$DEFVPS, PARM$DEFSNR,
     *		PARM$DEFPTR, PARM$DEFCNT, PARM$DEFLDEF, PARM$DEFADEF,
     *		PARM$VALLDYN, PARM$VALADYN, PARM$VALAVAL, PARM$VALASW,
     *		PARM$VALNRS, PARM$VALVPS, PARM$VALSNR, PARM$VALPTR,
     *		PARM$VALCNT, PARM$SAVLEN, PARM$SAVADR, PARM$KEYEND
C
C
	DATA PARM$LP /2/
	DATA PARM$STREAM /'$1'/
	DATA PARM$LS /2/
	DATA PARM$PROGSTRM /'NN$1_'/
	DATA PARM$LPS /4/
	DATA PARM$MODE /0/
	DATA PARM$PRC /0/
	DATA PARM$DEV /0/
	DATA PARM$SYSOUT /0/
	DATA PARM$NRKEY /0/
	DATA PARM$KEYLDYN /0/
	DATA PARM$KEYADYN /0/
	DATA PARM$KEYACUR /0/
	DATA PARM$LK /0/
	DATA PARM$PROGNAM /'NN'/
	END









