FROM newstar

# The following is only necessary for generating the documentation
USER root
RUN apt-get update && apt-get install -y imagemagick texlive-full
USER newstar
# Documentation: convert xbm into png since modern webbrowsers don't understand xbm
RUN cd $n_hlp && find . -name '*.xbm'  -exec sh -c 'convert $0 ${0%.xbm}.png' {} \;
RUN cd $n_hlp && find . -name '*.html' -exec sed -i -e 's/\.xbm/.png/g' {} \;

