C+ WNCTIM.FOR
C  WNB 890201
C
C  Revisions:
C	WNB 911115	DATA for CHARACTER problem
C
	SUBROUTINE WNCTIM(COUT,CLEN)
C
C  Convert a value to a string
C
C  Result:
C
C	CALL WNCTIM ( COUT_C*:O, CLEN_J:O)
C				Set current time as HH:MM:SS in COUT,
C				setting CLEN to the significant
C				length of COUT.
C	CALL WNCTIF ( COUT_C*:O, CLEN_J:O)
C				As TIM, but HH:MM:SS.SS.
C	CALL WNCTIN ( COUT_C*:O, CLEN_J:O)
C				As TIM, but HHMMSS.
C	CALL WNCDAT ( COUT_C*:O, CLEN_J:O)
C				As TIM, but DD-Mmm-YY.
C	CALL WNCDAF ( COUT_C*:O, CLEN_J:O)
C				As TIM, but DD-Mmm-YYYY.
C	CALL WNCDAN ( COUT_C*:O, CLEN_J:O)
C				As TIM, but YYMMDD.
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	CHARACTER*(*) COUT			!OUTPUT STRING
	INTEGER CLEN				!OUTPUT LENGTH
C
C  Function references:
C
C
C  Data declarations:
C
	CHARACTER*23 FIELD			!INTERNAL VALUE
	CHARACTER*36 MON
	CHARACTER*24 MONN
	  DATA MON/'JanFebMarAprMayJunJulAugSepOctNovDec'/
	  DATA MONN/'010203040506070809101112'/
C
C  Equivalences:
C
C
C  Commons:
C
C-
	CALL WNGSYT(FIELD)			!GET SYSTEM TIME
	COUT=FIELD(13:20)
	CLEN=8
C
	RETURN
C
C WNCTIF
C
	ENTRY WNCTIF(COUT,CLEN)
C
	CALL WNGSYT(FIELD)			!GET SYSTEM TIME
	COUT=FIELD(13:23)
	CLEN=11
C
	RETURN
C
C WNCTIN
C
	ENTRY WNCTIN(COUT,CLEN)
C
	CALL WNGSYT(FIELD)			!GET SYSTEM TIME
	COUT=FIELD(13:14)//FIELD(16:17)//FIELD(19:20)
	CLEN=6
C
	RETURN
C
C WNCDAT
C
	ENTRY WNCDAT(COUT,CLEN)
C
	CALL WNGSYT(FIELD)			!GET SYSTEM TIME
	COUT=FIELD(1:7)//FIELD(10:11)
	CLEN=9
C
	RETURN
C
C WNCDAF
C
	ENTRY WNCDAF(COUT,CLEN)
C
	CALL WNGSYT(FIELD)			!GET SYSTEM TIME
	COUT=FIELD(1:11)
	CLEN=11
C
	RETURN
C
C WNCDAN
C
	ENTRY WNCDAN(COUT,CLEN)
C
	CALL WNGSYT(FIELD)			!GET SYSTEM TIME
	I1=INDEX(MON,FIELD(4:6))/3		!MONTH
	COUT=FIELD(10:11)//MONN(2*I1+1:2*I1+2)//FIELD(1:2)
	CLEN=6
C
	RETURN
C
C
	END
