C+ WNGARI.FOR
C  WNB 890308
C
C  Revisions:
c	wnb 930520	Remove %VAL
C
	INTEGER*2 FUNCTION WNGARI(PARG,ARGL)
C
C  Get value from argument list
C
C  Result:
C
C	I = WNGARI ( PARG_J:I, ARGL_J(0:*):I) Get I value from PARG argument
C					in ARGL list, or zero if none available
C	J = WNGARJ ( PARG_J:I, ARGL_J(0:*):I) Get J value from PARG argument
C					in ARGL list, or zero if none available
C	K = WNGARK ( PARG_J:I, ARGL_J(0:*):I) Get K value from PARG argument
C					in ARGL list, or zero if none available
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER PARG				!ARGUMENT NUMBER
	INTEGER ARGL(0:*)			!ARGUMENT LIST
C
C  Entry points:
C
	INTEGER WNGARJ
	INTEGER*4 WNGARK
C
C  Function references:
C
	INTEGER*2 WNGGI				!CONVERT TO I
	INTEGER WNGGJ				!CONVERT TO J
	INTEGER*4 WNGGK				!CONVERT TO K
C
C  Data declarations:
C
C
C  Equivalences:
C
C
C  Commons:
C
C-
	WNGARI=0				!ASSUME NOT PRESENT
	IF (PARG.GT.0 .AND. PARG.LE.ARGL(0)) THEN !COULD BE PRESENT
	  IF (ARGL(PARG).NE.0) THEN		!ADDRESS PRESENT
	    WNGARI=WNGGI(A_B(ARGL(PARG)-A_OB))	!SET VALUE
	  END IF
	END IF
C
	RETURN
C
C WNGARJ
C
	ENTRY WNGARJ(PARG,ARGL)
C
	WNGARJ=0				!ASSUME NOT PRESENT
	IF (PARG.GT.0 .AND. PARG.LE.ARGL(0)) THEN !COULD BE PRESENT
	  IF (ARGL(PARG).NE.0) THEN		!ADDRESS PRESENT
	    WNGARJ=WNGGJ(A_B(ARGL(PARG)-A_OB))	!SET VALUE
	  END IF
	END IF
C
	RETURN
C
C WNGARK
C
	ENTRY WNGARK(PARG,ARGL)
C
	WNGARK=0				!ASSUME NOT PRESENT
	IF (PARG.GT.0 .AND. PARG.LE.ARGL(0)) THEN !COULD BE PRESENT
	  IF (ARGL(PARG).NE.0) THEN		!ADDRESS PRESENT
	    WNGARK=WNGGK(A_B(ARGL(PARG)-A_OB))	!SET VALUE
	  END IF
	END IF
C
	RETURN
C
C
	END
