C+ WNPDAC.FOR
C  WNB 910624
C
C  Revisions:
C
	LOGICAL FUNCTION WQDVAC(ID)
C
C  Activate device
C
C  Result:
C
C	WQDVAC_L = WQDVAC( ID_J:I)
C				Activate a plot device given by ID
C	WQDVDA_L = WQDVDA( ID_J:I)
C				De-activate the plot device given by ID.
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'WQG_DEF'		!GENERAL AREA
	INCLUDE	'WQD_O_DEF'		!DEVICE AREA
C
C  Parameters:
C
C
C  Entry points:
C
	LOGICAL WQDVDA		!DEACTIVATE DEVICE
C
C  Arguments:
C
	INTEGER ID		!PLOT ID
C
C  Function references:
C
	LOGICAL WNPCID		!CHECK ID
C
C  Data declarations:
C
C-
C
C INIT
C
	WQDVAC=.TRUE.					!ASSUME OK
	IF (WQG_STATE.EQ.4) THEN			!ILLEGAL STATE
 11	  CONTINUE
	  E_C=3
 10	  CONTINUE
	  WQDVAC=.FALSE.
	  RETURN
	END IF
C
C CHECK ID
C
	IF (.NOT.WNPCID(ID)) THEN			!NOT OPEN
 12	  CONTINUE
	  E_C=20
	  GOTO 10
	END IF
C
C CHECK OUTPUT
C
	IF (IAND(1,A_J((ID-A_OB)/LB_J+WQD_TYP_J)).EQ.0) THEN !NOT OUTPUT
	  E_C=34
	  GOTO 10
	END IF
C
C SET ACTIVE
C
	IF (A_J((ID-A_OB)/LB_J+WQD_ACT_J).EQ.0) THEN	!NOT ACTIVE
	  A_J((ID-A_OB)/LB_J+WQD_ACT_J)=1		!SET ACTIVE
	  WQG_NACT=WQG_NACT+1				!COUNT ACTIVE
	END IF
	IF (WQG_STATE.LT.3) WQG_STATE=3			!SET AT LEAST ONE ACTIVE
C
	RETURN
C
C WQDVDA
C
	ENTRY WQDVDA(ID)
C
C INIT
C
	WQDVDA=.TRUE.					!ASSUME OK
	IF (WQG_STATE.EQ.4) GOTO 11			!ILLEGAL STATE
C
C CHECK ID
C
	IF (.NOT.WNPCID(ID)) GOTO 12			!NOT OPEN
C
C DEACTIVATE DEVICE
C
	IF (A_J((ID-A_OB)/LB_J+WQD_ACT_J).NE.0) THEN	!ACTIVE
	  A_J((ID-A_OB)/LB_J+WQD_ACT_J)=0		!DE-ACTIVATE
	  WQG_NACT=WQG_NACT-1				!COUNT
	  IF (WQG_NACT.LE.0) THEN
	    WQG_STATE=2					!CORRECT STATE
	    WQG_NACT=0
	  END IF
	END IF
C
	RETURN
C
C
	END
