C+ WNTIO5.FOR
C  WNB 930501
C
C  Revisions:
C
	LOGICAL FUNCTION WNTIO5(FENTJ,IENTJ,N,LCOMB,LCOMM)
C
C  Give a comment line
C
C  Result:
C
C	WNTIO5_L = WNTIO5( FENTJ_J(0:*), IENTJ_J(0:*), N_J:IO,
C			LCOMB_B(0:*), LCOMM_C*:O)
C				Give next comment line (initially N=0, used
C				as count) for current Format ENTry in
C				LCOM. WNTIO5 is .false. if no comment
C				present; N<0 if no more comment lines
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'WNT_O_DEF'
	INCLUDE 'WNT_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER FENTJ(0:*)		!FORMAT ENTRY
	INTEGER IENTJ(0:*)		!INPUT LINE ENTRY
	INTEGER N			!COMMENT LINE COUNT
	CHARACTER*(*) LCOMM		!COMMENT
	  BYTE LCOMB(0:*)
C
C  Function references:
C
	INTEGER WNTIBR			!READ ENTRY
C
C  Data declarations:
C
C-
	WNTIO5=.TRUE.					!ASSUME OK
	LCOMM=' '					!COMMENT
	IF (N.LT.0) GOTO 900				!WERE ALREADY READY
	IF (N.EQ.0) THEN				!GET FIRST
	  IF (FENTJ(WNTF_ENT_J).GT.0) THEN		!LINE ENTRY
	    I2=WNTIBR(IBDES,IENTJ,FENTJ(WNTF_ENT_J))	!READ LINE
	    IF (IENTJ(WNTI_LCOM_J).GT.0) THEN		!COMMENT PRESENT
	      I2=WNTIBR(CBDES,LCOMB,IENTJ(WNTI_PCOM_J))	!READ IT
	    ELSE
	      WNTIO5=.FALSE.				!NO COMMENT
	    END IF
	    N=N+1					!COUNT IT
	  ELSE						!NONE AT ALL
	    N=-1
	    GOTO 900
	  END IF
	ELSE
	  I=FENTJ(WNTF_ENT_J)+N				!COMMENT ENTRY
	  IF (IENTJ(WNTI_FTYP_J).EQ.FT_CON) THEN	!MORE COMMENTS
	    I2=WNTIBR(IBDES,IENTJ,I)			!READ LINE
	    IF (IENTJ(WNTI_LCOM_J).GT.0) THEN		!COMMENT PRESENT
	      I2=WNTIBR(CBDES,LCOMB,IENTJ(WNTI_PCOM_J))	!READ IT
	    ELSE
	      WNTIO5=.FALSE.				!NO COMMENT
	    END IF
	    N=N+1
	  ELSE
	    N=-1					!READY
	    GOTO 900
	  END IF
	END IF						!ENTRY
C
C READY
C
	RETURN
C
C ERRORS
C
 900	CONTINUE
	WNTIO5=.FALSE.
C
	RETURN
C
C
	END
