C+ WNTIOL.FOR
C  WNB 930501
C
C  Revisions:
C
	SUBROUTINE WNTIOL
C
C  Output .DSC structures in log
C
C  Result:
C
C	CALL WNTIOL	outputs the structure and common parts of the .DSC
C			output in log, to give overview of offsets
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'WNT_O_DEF'
	INCLUDE 'WNT_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
C
C  Function references:
C
	INTEGER WNCALN			!STRING LENGTH
	INTEGER WNTIBR			!READ ENTRY
	LOGICAL WNTIO5			!GET COMMENT LINE
C
C  Data declarations:
C
	INTEGER OF1,OF2			!PRINT OFFSETS
	INTEGER NCOM			!COMMENT COUNT
	CHARACTER*(MXLNAM) LNAM,LNAM1,LNAM2,LNAM3 !LOCAL DATA
	CHARACTER*(MXLNAM) LCNAM	!LC NAME
	CHARACTER*(MXLNAM) CNAM		!COMMON NAME
	CHARACTER*(MXSLIN) LCOMM	!OUTPUT COMMENT
	  BYTE LCOMB(0:MXSLIN-1)
	  EQUIVALENCE (LCOMM,LCOMB)
	BYTE FENTB(0:WNTFHDL-1)		!FORMAT ENTRY
	  INTEGER FENTJ(0:WNTFHDL/LB_J-1)
	  EQUIVALENCE (FENTB,FENTJ)
	BYTE LFENTB(0:WNTFHDL-1)	!LOCAL FORMAT ENTRY
	  INTEGER LFENTJ(0:WNTFHDL/LB_J-1)
	  EQUIVALENCE (LFENTB,LFENTJ)
	BYTE LIENTB(0:WNTIHDL-1)	!LOCAL LINE ENTRY
	  INTEGER LIENTJ(0:WNTIHDL/LB_J-1)
	  EQUIVALENCE (LIENTB,LIENTJ)
C-
C
C INIT
C
	OF1=3						!PRINT OFFSETS
	OF2=19
	CALL WNCFHD(F_P,5,'!7COffset!20CName!40CType!65CLength'//
	1		'!75CDescription')
	CALL WNCFHD(F_P,6,' ')
C
C OUTPUT COMMONS
C
	IF (DEFSN) THEN					!COULD BE COMMON
	  CNAM=' '					!NO COMMON
	  DO I1=0,XFDES_J(WNTB_CNT_J)-1			!ALL ENTRIES
	    I2=WNTIBR(XFDES,FENTB,I1)			!READ ENTRY
	    IF (FENTJ(WNTF_BTYP_J).EQ.BT_DCM) THEN	!NEW COMMON
	      CALL WNTIO1(0,FENTB,CNAM,CNAM,LCNAM)	!GET NAME
	      CALL WNCFHD(F_P,3,'!16CContents of !AS_COM'//
	1		' (Length= !UJ User= !AS,'//
	1		' Date= !AS, Version= !AS, System= !AS)',
	1		CNAM,FENTJ(WNTF_TLEN_J),PARM(P_USE),PARM(P_DAT),
	1		PARM(P_VER),PARM(P_SYS))
	      CALL WNCTXT(F_P,'!^')			!NEW PAGE
	    ELSE IF (FENTJ(WNTF_BTYP_J).EQ.BT_COM .AND.
	1		FENTJ(WNTF_DTP_J).NE.0 .AND.
	1		FENTB(WNTF_NAM_1).NE.ICHAR('-')) THEN
	      CALL WNTIO0(0,FENTJ,LNAM)			!ARRAY STRING
	      IF (FENTJ(WNTF_REFP_J).GT.0 .AND.
	1		FENTJ(WNTF_REFP_J).LT.I1) THEN	!= REFERENCE
	        I2=WNTIBR(XFDES,LFENTB,FENTJ(WNTF_REFP_J)) !READ REF. ENTRY
		CALL WNCTXS(LNAM1,'=!AD',
	1		LFENTB(WNTF_NAM_1),WNTF_NAM_N)
	      ELSE
	        LNAM1=' '
	      END IF
	      NCOM=0					!GET FIRST COMMENT
	      JS=WNTIO5(FENTJ,LIENTJ,NCOM,LCOMB,LCOMM)
	      IF (FENTJ(WNTF_DTP_J).EQ.T_S) THEN	!STRUCTURE
	        I2=WNTIBR(XFDES,LFENTB,FENTJ(WNTF_SREF_J)) !READ REF. ENTRY
		CALL WNCTXS(LNAM2,'!AS:!AD',
	1		CD1(FENTJ(WNTF_DTP_J)),
	1		LFENTB(WNTF_NAM_1),WNTF_NAM_N)
	      ELSE
		LNAM2=CD1(FENTJ(WNTF_DTP_J))
	      END IF
	      IF (FENTJ(WNTF_REFP_J).GT.0 .AND.
	1		FENTJ(WNTF_REFP_J).LT.I1) THEN	!= REFERENCE
		LNAM3='='
	      ELSE
		LNAM3=' '
	      END IF
	      IF (FENTJ(WNTF_DTP_J).NE.T_C) THEN	!NUMERIC
	        CALL WNCTXT(F_P,'!3C!4$UJ !4$XJ!AS!19C!AD!AS!39C!AS!51C!AS'//
	1		'!65C!4$UJ!75C!AS',
	1		FENTJ(WNTF_OFF_J),FENTJ(WNTF_OFF_J),LNAM3,
	1		FENTB(WNTF_NAM_1),WNTF_NAM_N,LNAM1,
	1		LNAM2,LNAM,
	1		FENTJ(WNTF_TLEN_J)*FENTJ(WNTF_ULEN_J),
	1		LCOMM)
	      ELSE					!CHARACTER
	        CALL WNCTXT(F_P,'!3C!4$UJ !4$XJ!AS!19C!AD!39C!AS!UJ!51C!AS'//
	1		'!65C!4$UJ!75C!AS',
	1		FENTJ(WNTF_OFF_J),FENTJ(WNTF_OFF_J),LNAM3,
	1		FENTB(WNTF_NAM_1),WNTF_NAM_N,
	1		CD1(FENTJ(WNTF_DTP_J)),FENTJ(WNTF_SLEN_J),LNAM,
	1		FENTJ(WNTF_TLEN_J)*FENTJ(WNTF_SLEN_J),
	1		LCOMM)
	      END IF
	      DO WHILE (NCOM.GE.0)			!MORE COMMENTS?
		IF (WNTIO5(FENTJ,LIENTJ,NCOM,LCOMB,LCOMM)) THEN
		  CALL WNCTXT(F_P,'!75C!AS',LCOMM)
		END IF
	      END DO
	    END IF					!ENTRY
	  END DO					!ALL ENTRIES
	END IF						!DEF SEEN
C
C OUTPUT STRUCTURES
C
	IF (BEGSN) THEN					!STRUCTURES PRESENT
	  CNAM=' '					!NO NAME
	  CALL WNCFHD(F_P,3,'!16CContents of structures for !AS$.DSC'//
	1		' (User= !AS,'//
	1		' Date= !AS, Version= !AS, System= !AS)',
	1		PARM(P_NAM),PARM(P_USE),PARM(P_DAT),
	1		PARM(P_VER),PARM(P_SYS))
	  CALL WNCTXT(F_P,'!^')				!NEW PAGE
	  DO I1=0,XFDES_J(WNTB_CNT_J)-1			!ALL ENTRIES
	    I2=WNTIBR(XFDES,FENTB,I1)			!READ ENTRY
	    IF (FENTJ(WNTF_BTYP_J).EQ.BT_BEG) THEN	!NEW STRUCTURE
	      CALL WNTIO1(0,FENTB,CNAM,CNAM,LCNAM)	!NAME
	      CALL WNCTXT(F_P,'!#C!4$UJ !4$XJ!#C$(!AS!64C!5$UJ',
	1		OF1,0,0,OF2,CNAM,
	1		FENTJ(WNTF_TLEN_J))
	      OF1=OF1+2					!NEW PRINT OFFSETS
	      OF2=OF2+2
	    ELSE IF (FENTJ(WNTF_BTYP_J).EQ.BT_EBG) THEN	!END STRUCTURE
	      OF1=OF1-2					!NEW PRINT OFFSETS
	      OF2=OF2-2
	      CALL WNCTXT(F_P,'!#C$)',
	1		OF2)
	    ELSE IF (FENTJ(WNTF_BTYP_J).EQ.BT_SDA .AND.
	1		FENTJ(WNTF_DTP_J).NE.0) THEN	!DATA ENTRY
	      CALL WNGMTS(WNTF_NAM_N,FENTB(WNTF_NAM_1),LNAM1) !NAME
	      IF (LNAM1(1:1).EQ.'-') LNAM1='-'
	      CALL WNTIO0(0,FENTJ,LNAM)			!ARRAY STRING
	      NCOM=0					!GET FIRST COMMENT
	      JS=WNTIO5(FENTJ,LIENTJ,NCOM,LCOMB,LCOMM)
	      IF (FENTJ(WNTF_DTP_J).EQ.T_S) THEN	!STRUCTURE
	        I2=WNTIBR(XFDES,LFENTB,FENTJ(WNTF_SREF_J)) !READ REF. ENTRY
		CALL WNCTXS(LNAM2,'!AS:!AD',
	1		CD1(FENTJ(WNTF_DTP_J)),
	1		LFENTB(WNTF_NAM_1),WNTF_NAM_N)
	      ELSE
		LNAM2=CD1(FENTJ(WNTF_DTP_J))
	      END IF
	      IF (FENTJ(WNTF_REFP_J).GT.0 .AND.
	1		FENTJ(WNTF_REFP_J).LT.I1) THEN	!= REFERENCE
		LNAM3='='
	      ELSE
		LNAM3=' '
	      END IF
	      IF (FENTJ(WNTF_DTP_J).NE.T_C) THEN	!NUMERIC
	        CALL WNCTXT(F_P,'!#C!4$UJ !4$XJ!AS!#C!AS!39C!AS!51C!AS'//
	1		'!65C!4$UJ!75C!AS',
	1		OF1,FENTJ(WNTF_OFF_J),FENTJ(WNTF_OFF_J),LNAM3,
	1		OF2,LNAM1,
	1		LNAM2,LNAM,
	1		FENTJ(WNTF_TLEN_J)*FENTJ(WNTF_ULEN_J),
	1		LCOMM)
	      ELSE					!CHARACTER
	        CALL WNCTXT(F_P,'!#C!4$UJ !4$XJ!AS!#C!AS!39C!AS!UJ!51C!AS'//
	1		'!65C!4$UJ!75C!AS',
	1		OF1,FENTJ(WNTF_OFF_J),FENTJ(WNTF_OFF_J),LNAM3,
	1		OF2,LNAM1,
	1		CD1(FENTJ(WNTF_DTP_J)),FENTJ(WNTF_SLEN_J),LNAM,
	1		FENTJ(WNTF_TLEN_J)*FENTJ(WNTF_ULEN_J)*
	1		FENTJ(WNTF_SLEN_J),
	1		LCOMM)
	      END IF
	      DO WHILE (NCOM.GE.0)			!MORE COMMENTS?
		IF (WNTIO5(FENTJ,LIENTJ,NCOM,LCOMB,LCOMM)) THEN
		  CALL WNCTXT(F_P,'!75C!AS',LCOMM)
		END IF
	      END DO
	    END IF					!ENTRY TYPE
	  END DO					!ALL ENTRIES
	  CALL WNCTXT(F_P,'!2/Symbols used in the above description:')
	  CALL WNCTXT(F_P,'!/( = .STRUCTURE!25C) = .END'//
	1		'!50C$= = EQUIVALENCE!/')
	END IF						!BEG SEEN
C
C READY
C
 800	CONTINUE
	CALL WNCFHD(F_P,-6,' ')				!DELETE POSSIBLE HEAD
	CALL WNCFHD(F_P,-5,' ')
	CALL WNCFHD(F_P,-3,' ')
C
	RETURN
C
C ERRORS
C
 900	CONTINUE
C
	RETURN
C
C
	END
