C+ WNTIA1.FOR
C  WNB 930501
C
C  Revisions:
C
	SUBROUTINE WNTIA1(DLEN)
C
C  Help routine to create a dummy fill format line
C
C  Result:
C
C	CALL WNTIA1( DLEN_J:I)
C				Create a dummy data line for filling with
C				length DLEN
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'WNT_O_DEF'
	INCLUDE 'WNT_DEF'
C
C  Parameters:
C
C
C  Arguments:
C
	INTEGER DLEN		!LENGTH TO FILL
C
C  Function references:
C
	INTEGER WNTIBP		!WRITE ENTRY IN TABLE
C
C  Data declarations:
C
	BYTE FENTB(0:WNTFHDL-1)	!ENTRY FILLED
	  CHARACTER*(WNTFHDL) FENTC
	  INTEGER FENTJ(0:WNTFHDL/LB_J-1)
	  EQUIVALENCE (FENTB,FENTC,FENTJ)
C-
C
C CHECK
C
	IF (DLEN.LE.0) GOTO 800			!NOTHING TO DO
C
C MAKE FILLER
C
	CALL WNGMVZ(WNTFHDL,FENTJ)		!CLEAN
	FENTJ(WNTF_BTYP_J)=CBTP			!BLOCK TYPE
	FENTJ(WNTF_ALEN_J)=LB_B			!ALIGN LENGTH
	FENTJ(WNTF_DTP_J)=T_B			!DATA TYPE
	FENTJ(WNTF_ULEN_J)=LB_B			!UNIT LENGTH
	FENTJ(WNTF_DIM_J)=1			!DIMENSION
	FENTJ(WNTF_TLEN_J)=DLEN			!LENGTH TO FILL
	FENTJ(WNTF_OFF_J)=COFF			!OFFSET
	FENTJ(WNTF_IND_J+1)=DLEN		!LENGTH ARRAY
	CALL WNCTXS(FENTC(WNTF_NAM_1+1:WNTF_NAM_1+WNTF_NAM_N),
	1		'-__!4$ZJ',UNID)	!DUMMY NAME
	UNID=UNID+1				!COUNT DUMMY NAME
C
C WRITE FILLER
C
	I=WNTIBP(XFDES,FENTB)			!WRITE FILLER LINE
	COFF=COFF+DLEN				!NEW OFFSET
C
C FINISH
C
 800	CONTINUE
C
	RETURN
C
C
	END
