C+ NGCPBR.FOR
C  WNB 920820
C
C  Revisions:
C	HjV 930423	Change name of some keywords
C	WNB 930628	Change SCN_SETS into NGF_SETS
C	CMV 931220	Pass FCA of input file to WNDXLP and WNDSTA/Q
C	JPH 940822	FULL option, make BRIEF truly brief
C
C
	SUBROUTINE NGCPBR
C
C  Show brief data in NGF file
C
C  Result:
C
C	CALL NGCPBR	will show data in NGF file
C
C  PIN references:
C
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NGC_DEF'
	INCLUDE 'NGF_O_DEF'		!PLOT HEADER
C
C  Parameters:
C
C
C  Arguments:
C
C
C  Function references:
C
	LOGICAL WNDSTA			!GET PLOTS TO DO
	CHARACTER*32 WNTTSG		!SET NAME
	LOGICAL NGCSTG			!GET A PLOT
C
C  Data declarations:
C
	INTEGER NGFP			!SUB-GROUP POINTER
	INTEGER SNAM(0:7)		!SET NAME
	BYTE NGF(0:NGFHDL-1)		!PLOT HEADER
	INTEGER SAVNAM(0:7)		!PREVIOUS SNAM
	BYTE SAVNGF(NGFHDL)
	INTEGER CNT(3:5)		!CUT COUNTERS
C-
C
C DO PLOTS
C
	CALL WNCTXT(F_TP,' ')
	IF (.NOT.WNDSTA('NGF_SETS',MXNSET,SETS,FCAOUT))
	1	 GOTO 900 			!GET SETS TO DO

	SAVNAM(0)=-1				! INIT INVALID
	DO WHILE(NGCSTG(FCAOUT,SETS,NGF,NGFP,SNAM)) !GET CUT
	  IF (SAVNAM(0).NE.SNAM(0)
	1	.OR.SAVNAM(1).NE.SNAM(1)
	1	.OR.SAVNAM(2).NE.SNAM(2)) THEN
	    IF (SAVNAM(0).GE.0) CALL NGCSPC(SAVNAM,SAVNGF,CNT)
	    CNT(3)=0				! NEW CHN, INIT COUNTS
	    CNT(4)=0
	    CNT(5)=0
	    CALL WNGMV(NGFHDL,NGF,SAVNGF)	! SAVE HEADER
	  ENDIF
	  IF (SAVNAM(3).NE.SNAM(3) .OR. CNT(3).EQ.0) THEN
	    CNT(3)=CNT(3)+1			! NEW POL
	    CNT(4)=CNT(4)+1			!  AND IORT
	  ELSEIF (SAVNAM(4).NE.SNAM(4)) THEN
	    CNT(4)=CNT(4)+1			! NEW IORT
	  ENDIF
	  CNT(5)=CNT(5)+1			! NEW CUT
	  DO I=0,5
	    SAVNAM(I)=SNAM(I)
	  ENDDO
	END DO
	IF (OPT.EQ.'BRI') CALL NGCSPC(SAVNAM,SAVNGF,CNT)
	IF (OPT.EQ.'FUL') CALL NGCSPH(SAVNAM,SAVNGF)
	CALL WNCTXT(F_TP,' ')
C
C READY
C
 900	CONTINUE
C
	RETURN
C
C
	END
