!+ MPH.DSC
!  WNB 910219
!
!  Revisions:
!
%REVISION=CMV=940517="Add JOBP (pointer to job-summary)"
%REVISION=WNB=931216="Add some edit formats"
%REVISION=WNB=931015="Use SSH"
%REVISION=WNB=930803="Text only"
%REVISION=WNB=920828="Add VELC, VELR, FRQ0, FRQV, FRQC, INST"
%REVISION=WNB=920818="Add VEL"
%REVISION=WNB=910219="Original version"
!
!	Define Map Header block
!
%COMMENT="MPH.DSC defines the map header block"
%COMMENT=" "
!
%VERSION=1					!VERSION
%SYSTEM=1
%USER=WNB
%%DATE
%%NAME
!-
.PARAMETER
.BEGIN=MPH
%INCLUDE=SSH_DSF				!STANDARD AREA
	FNM	C12				!FIELD NAME
	EPO	E		<E12.1>		!EPOCH (E.G. 1950.0)
	RA	D		<DAF12.7>	!RIGHT ASCENSION (CIRCLES)
	DEC	D		<DAF12.7>	!DECLINATION (CIRCLES)
	FRQ	D		<D12.6>		!FREQUENCY (MHZ)
	BDW	D		<D12.6>		!BANDWIDTH (MHZ)
	RAO	D		<DAF12.7>	!OBSERVED RIGHT ASCENSION (CIR)
	DECO	D		<DAF12.7>	!OBSERVED DECL. (CIRCLES)
	FRQO	D		<D12.6>		!OBSERVED FREQ. (MHZ)
	ODY	I				!OBSERVED DAY SINCE JAN 0
	OYR	I				!OBSERVED YEAR OR 0 (E.G. 1985)
	DCD	I				!DATA CODE:
						! 2= I
						! 4= J
						! 5= E
						! 8= D
	PCD	I				!PROGRAM CODE:	0= NMAP
	SRA	D		<DAF12.7,1>	!SEPARATION IN RA (CIRCLES)
	SDEC	D		<DAF12.7,1>	!SEPARATION DEC (CIRCLES)
	SFRQ	D		<D12.6>		!SEPARATION FREQ. (MHZ)
	NRA	J		<,1>		!# OF POINTS IN RA
	NDEC	J		<,1>		!# OF POINTS IN DEC
	NFRQ	J		<,1>		!# OF POINTS IN FREQ.
	ZRA	J				!CENTRE RA (1ST POINT=0)
	ZDEC	J				!CENTRE DEC (1ST LINE=0)
	ZFRQ	J				!CENTRE FREQUENCY (1ST MAP=0)
	MXR	J				!POSITION MAX. IN RA
	MXD	J				!POSITION MAX. IN DEC
	MXF	J				!POSITION MAX. IN FREQUENCY
	MNR	J				!POS. MIN. RA
	MND	J				!POS. MIN. DEC
	MNF	J				!POS. MIN. FREQ.
	MAX	E		<E12.3>		!MAX. IN MAPS
	MIN	E		<E12.3>		!MIN. IN MAPS
	SHR	D		<DAF12.7>	!SHIFT IN RA (ADD, CIRCLES)
	SHD	D		<DAF12.7>	!SHIFT IN DEC (ADD, CIRCLES)
	SHF	D		<D12.6>		!SHIFT IN FREQ. (ADD, MHZ)
	SUM	D		<D12.6>		!NORMALISING SUM
	UNI	E		<E12.1>		!MULTIPLIER TO GET JY
	UCM	C24				!USER COMMENT
	NPT	J				!# OF INPUT DATA POINTS
	TYP	C4				!MAP TYPE (MAP, AP, COV ETC)
	POL	C2				!POL. TYPE (OR SO)
	CD	I(0:7)				! 0: TAPER TYPE
						! 1: CONVOLUTION TYPE
						! 2: CORRECT FOR CONVOLUTION
						! 3: CLIPPING DONE
						! 4: SOURCE SUBTRACTION
						! 5: DATA TYPE
						! 6: UV COORDINATE TYPE
						! 7: DE-BEAM COUNT
	EPT	I				!MAP EPOCH USED:
						! 0: APPARENT
						! 1: AS SPECIFIED IN EPOCH
	OEP	E		<E12.2>		!OBSERVATION EPOCH (EG 1985.78)
	NOS	E		<E12.3>		!MAP NOISE (W.U.)
	FRA	E		<EAF12.4>	!FIELD SIZE RA (CIRCLES)
	FDEC 	E		<EAF12.4>	!FIELD SIZE DEC (CIRCLES)
	FFRQ	E		<E12.3>		!FIELD SIZE FREQ (MHZ)
	TEL	C8				!NAME OF TELESCOPE
	FSR	J				!FFT SIZE RA
	FSD	J				!FFT SIZE DEC
	MDP	J		<XJ,1>		!MAP DATA POINTER
	NBL	J				!# OF BASELINES IN MAP
	NST	J				!# OF SETS IN MAP
	VEL	E		<E12.1>		!VELOCITY IN M/S
	VELC	J				!VELOCITY CODE:
						! 0= CONTINUUM
						! 1= HELIOCENTRIC RADIO
						! 2= LSR RADIO
						! 3= HELIOCENTRIC OPTICAL
						! 4= LSR OPTICAL
	VELR	E		<E12.4>		!VELOCITY AT REF. FREQ. (FRQC)
	INST	J				!INSTRUMENT:
						! 0= WSRT
						! 1= ATCA
	FRQ0	D		<D12.6>		!REST FREQUENCY FOR LINE (MHZ)
	FRQV	D		<D12.6>		!REAL FREQUENCY FOR LINE (MHZ)
	FRQC	D		<D12.6>		!CENTRE FREQUENCY FOR LINE (MHZ)
	JOBP	J		<XJ,1>		!POINTER TO JOB SUMMARY LOG
	JOBL	J		<XJ,1>		!LENGTH (IN BYTES) OF LOG
	-	-(152)				!RESERVED
.END
!-
