!+ NMA.DSC
!  WNB 910219
!
!  Revisions:
!
%REVISION=CMV=951127="Add CSUM and RSUM, add MXRMVAL, RMVAL"
%REVISION=WNB=950817="Add BSTEP for polarised intensity"
%REVISION=WNB=950809="Add NPTRF for polarised intensity"
%REVISION=WNB=950120="Add %ALIGN to cater for wrong IUNIT etc"
%REVISION=JPH=940930="Add CENTRE, change LSHIFT; comments"
%REVISION=HjV=940714="Add IUNIT, ILAB, NLAB, MXNLAB"
%REVISION=CMV=940530="Add JOBSUM"
%REVISION=WNB=930930="Add Fiddle type codes"
%REVISION=WNB=930826="Add POLTJ"
%REVISION=WNB=930803="Remove .INCLUDE"
%REVISION=WNB=930602="Add BEMLIM"
%REVISION=WNB=930127="Add proper bandwidth"
%REVISION=WNB=921104="Add J2000"
%REVISION=WNB=920828="Change length CNTDVL"
%REVISION=WNB=920817="Add CWGTYP and CWGVAL"
%REVISION=WNB=910219="Original version"
!
!	Layout of overall include file (NMA.DEF)
!
%COMMENT="NMA.DEF is an INCLUDE file for the NMAP program"
%COMMENT=" "
!
%VERSION=1
%SYSTEM=1
%USER=WNB
%%DATE
%%NAME
%LOCAL=STHTEL=14			!# OF TELESCOPES
!
%GLOBAL=MXNFIL=8			!MAX. # OF INPUT FILE SETS
%GLOBAL=MXNSET=16			!MAX. # OF SETS PER INPUT JOB
%GLOBAL=MXSBB=2048			!SIZE SINGLE SORTING BUFFER
%GLOBAL=MXSBJ=MXSBB/LB_J		!SIZE SORTING BUFFER IN J
%GLOBAL=DFTSIZ=17			!SIZE DFT (MUST BE ODD)
%GLOBAL=CNTJ=7				!# OF COUNTS AND AVERAGES
%GLOBAL=CNTD=16				!# OF AVERAGES
%GLOBAL=CNTC=2				!# OF CHARACTER DATA
%GLOBAL=CVLSTP=32			!# OF GRID POINTS PER CONVOL. STEP
%GLOBAL=NOPT=7				!# OF POSSIBLE OUTPUTS
%GLOBAL=MXNLAB=256			!MAX. # OF LABS 
%GLOBAL=NPTRF=4096			!LENGTH FOURIER TRANSFORM FOR POL. INT
%GLOBAL=MXRMVAL=512			!MAX NUMBER OF RM VALUES
!-
!
! Make sure common block correctly aligned
!
%ALIGN
!
.DEFINE
  .PARAMETER
	ORDOPT	C(3*NOPT)	/MAPAPTCOVREAIMAAMPPHA/ !OUTPUT OPTION ORDER
	BEMLIM	D		/0.01/		!LOWEST BEAM VALUE USED
	BSTEP	E		/1.5/		!STEP FOR POL. INT CONVOLUTION
!
! Fiddle types
!
	FID	A:(0)		/ADD,AVERAGE/	!ADDING
	FID	A*:(3)		/POLAR,ANGLE/	!POLARISATION
	FID	A*:(10)		/SUM,NSUM,BSUM,BNSUM,FSUM,NSSUM,CSUM,RSUM/ !SUMMING
	FID	A*:(20)		/EXTRACT,COPY/	!COPYING
	FID	A*:(100)	/BEAM,DEBEAM,FACTOR/ !MULTIPLICATION
	FID	A*:(200)	/MOSCOM,LMMOS,RAMOS/ !MOSAIC
	FID	A*:(300)	/RHOLOG,WMP/	!LOAD
	FID	A*:(310)	/UNLOAD/	!UNLOAD
	FID	A*:(-1)		/DUMMY/		!DUMMY
  .DATA
!
!  Local variables:
!
  .COMMON
	OPTION	C24				!PROGRAM OPTION
	OPT=OPTION C3
	MEMSIZ	J				!SIZE OF DYNAMIC MEMORY TO USE
	LFLDS	J(0:1)				!LOOP OUTPUT FIELDS
	LCHANS	J(0:1)				!LOOP OUTPUT CHANNELS
	NFILE	J				!# OF INPUT FILE GROUPS
	IUNIT	C1				!INPUT UNIT
	ILAB	J(MXNLAB)			!LABELS TO DO
	NLAB	J				!# OF LABELS TO DO
	NODIN	C80(MXNFIL)			!INPUT NODE
	FILIN	C160(MXNFIL)			!INPUT FILE
	FCATAP	J				!TAPE FILE
	OLABEL	J				!OUTPUT TAPE LABEL
	OUNIT	C1				!OUTPUT UNIT
	OUNRS	C3				!FILL
	SETS	J(0:7,0:MXNSET,MXNFIL)		!SETS PER JOB
	HA	E(0:1,MXNFIL)			!HA-RANGE PER JOB
	SIFRS	B(0:STHTEL-1,0:STHTEL-1,MXNFIL)	!SELECT INTERFEROMETERS
	FCAOUT	J				!OUTPUT FCA
	NODOUT	C80				!OUTPUT NODE
	FILOUT	C160				!OUTPUT FILE
	OUTOPT	L(NOPT)				!SELECTED UV PLANE OUTPUTS:
						! 1= MAP
						! 2= AP
						! 3= COVER
						! 4= REAL PLANE
						! 5= IMAG. PLANE
						! 6= AMPL. PLANE
						! 7= PHASE PLANE
	NPOL	J				!# OF OUTPUT POLARISATIONS
	POLC	C4(0:3)				!POLARISATION CODES
	POLT	E(-2:3,0:3)			!POLARISATION TRANSLATION:
						! -2: IMAGINARY MULTIPLIER
						! -1: MIN. # TO BE PRESENT
						! 0..:XX,XY,YX,YY FACTOR
	  POLTJ=POLT J(-2:3,0:3)
	DODFT	L				!DO DFT I.S.O. FFT
	UVCDT	J				!UV COORDINATE TYPE:
						! 0= STANDARD
						! 1= BAS-HA
						! 2= IFR-HA
	UVDTP	J				!UV DATA TYPE:
						! 0= STANDARD
						! 1= MODEL
	UWGT	J				!UV WEIGHTING TYPE:
						! 0= NATURAL
						! 1= STANDARD
						! 2= FULL
	DATTYP	J				!UV DATA TYPE:
						! 1= NORMAL
						! 2= COSINE
						! 3= SINE
						! 4= AMPLITUDE
						! 5= PHASE
	FIELD	E(0:1)				! FIELD SIZE (RADIANS)
	CVLTYP	J				! CONVOLUTION TYPE:
						! 1= GAUSSIAN
						! 2= BOX
						! 3= PROLATE 4*4
						! 4= EXPSINC
						! 5= PROLATE 6*6
	CVLWID	E(0:1)				!HALF CONVOLUTION WIDTH (CELLS)
	DECVL	L				!APPLY DECONVOLVE FACTOR
	FTSIZ	J(0:1)				!FFT SIZE (CELLS, POWER OF 2)
	OUTSIZ	J(0:1)				!OUTPUT SIZE (CELLS)
	CAP	J				!APPLY CORRECTIONS CODE
	CDAP	J				!DE-APPLY CORRECTIONS CODE
	MAKMAP	L				!MAKE A MAP
	MAKAP	L				!MAKE AN ANTENNA PATTERN
	TAPTYP	J				!TAPER TYPE
						! 1= GAUSSIAN
						! 2= LINEAR
						! 3= NATURAL
						! 4= OVERR
						! 5= RGAUSS
	TAPVAL	E				!TAPER VALUE (M)
	MAPCTP	J				!COORDINATE TYPES:
						! -2= REF. B1950
						! -1= REF. APPARENT
						!  1= APPARENT
						!  2= B1950
	MAPCRD	D(0:1)				!RA/DEC MAP CENTRE per map
	SUB	L				! SUBTRACT SOURCES
	UVRAD	E(0:1)				! inner and outer radii of UV
						!  annulus selected
	CLIP	L				! CLIP DATA
	CLPRAD	E(0:1)				! inner and outer radii of UV
						!  annulus for clipping
	CLPLEV	E(0:1)				! CLIP LEVELS
	LSHIFT	J				! SHIFT FIELD: 0=no, 1=shift,
						!  -1=centre
	SHIFT	E(0:1)				! FIELD SHIFT
	CENTRE	D(0:1)				! field centre
	BEMFAC	E(0:1,0:5)			! BEAM FACTORS
	CWGTYP	J				! CIRC. WEIGHT TYPE
						!    0=natural, 1=gaussian, 
						!    2=triangular
	CWGVAL	E				! CIRC. WEIGHT VALUE
	RES1	J
!
!  History
!
!  Loops
!
	LPOFF	J(0:7)				!CURRENT SET OFFSETS
!
!  Sorting
!
	NBIN	J				!# OF SORTING BINS
	BINSIZ	J				!U EXTEND PER SORTING BIN
	BINADM	J				!ADDRESS BIN ADMINISTRATION
						! 1= PTR IN BUFFER
						! 2= CURRENT BUFFER FOR BIN (OR -1)
						! 3= LAST POSSIBLE ENTRY IN THIS BUFFER
						! 4= PTR PREVIOUS BUFFER (OR -1)
	BINBUF	J				!ADDRESS BIN BUFFER
						! LAST ADDRESS= PTR PREVIOUS DISK
!
!  DFTing
!
	DFTBFA	J(0:3)				!BUFFERS FOR DFT
	DFTWT	E(0:3)				!TOTAL WEIGHTS DFT
!
!  Convolution
!
	UHIGH	J				!HIGHEST U COORD. (CELLS)
	VLOW	J				!LOWEST V COORD. (CELLS)
	VHIGH	J				!HIGHEST V COORD. (CELLS)
	USIZE	J				!# OF LINES PER CONVOL. BIN
	VSIZE	J				!# OF POINTS PER CONVOL. LINE
	ULOB	J				!LOW BOUND CURRENT CONVOL. BIN
	DECVB	J(0:1)				!BUFFERS DECONVOLUTION
!
	UVMAX	E(0:1)				!MAX. U,V
	UV1MAX	E(0:1)				!MAX. U,V FOR BAS-HA TYPE
	UV2MAX	E(0:1)				!MAX. U,V FOR IFR-HA TYPE
	UVCMAX	J(0:1)				!MAX. U,V COORDINATE
	UVSC	E				!U,V INTERNAL SCALE
	FRQMAX	E				!MAX. FREQUENCY IN INPUT
	FRQMIN	E				!MIN. FREQUENCY IN INPUT
!
	CNTJVL	J(0:CNTJ-1)			!AVERAGE VALUES AND COUNTS:
						! 0= OBS. DAY
						! 1= OBS. YEAR
						! 2= SET COUNT
						! 3= VELOCITY TYPE
						! 4= DATA POINT COUNT
						! 5= BASELINE COUNT
						! 6= INSTRUMENT TYPE
	CNTDVL	D(0:CNTD-1)			!AVERAGE VALUES AND COUNTS:
						! 0= OBS. RA FIRST SET
						! 1= OBS. DEC FIRST SET
						! 2= EPOCH RA FIRST SET
						! 3= EPOCH DEC FIRST SET
						! 4= EPOCH
						! 5= TOTAL AVERAGE BANDWIDTH
						! 6= AVERAGE WEIGHTED FREQUENCY
						! 7= VELOCITY
						! 8= REF. VELOCITY
						! 9= REF. LINE FREQUENCY
						!10= RESID. MOSAIC L SHIFT
						!11= RESID. MOSAIC M SHIFT
						!12= REST. LINE FREQ.
						!13= 1950/2000
						!14= AVERAGE BANDWIDTH
!
	SUM	D				!NORMALIZING SUM
	SGPH	J(0:7)				!SUB-GROUP POINTER
	SGNR	J(0:7)				!SUB-GROUP NUMBER
	CNTCVL	C24(0:CNTC-1)			!CHARACTER DATA:
						! 0= FIELDNAME
						! 1= USER COMMENT
!
	JOBSUM	J(0:1)				!PTR/LENGTH JOB SUMMARY
	RMVAL	E(0:MXRMVAL-1)			!ROTATION MEASURE VALUES
.END
