C+ NMAXCV.FOR
C  WNB 910327
C
C  Revisions:
C       CMV 940422	Use correct pointer to convert map-data
C       HJV 940518	Better DCD test
C
	SUBROUTINE NMAXCV
C
C  Convert WMP file from VAX to local format
C
C  Result:
C
C	CALL NMAXCV	will convert a WMP file from VAX to local format
C
C  Include files:
C
	INCLUDE 'WNG_DEF'
	INCLUDE 'NMA_DEF'
	INCLUDE 'GFH_O_DEF'		!GENERAL FILE HEADER
	INCLUDE 'GFH_T_DEF'
	INCLUDE 'SGH_O_DEF'		!SUB-GROUP HEADER
	INCLUDE 'SGH_T_DEF'
	INCLUDE 'MPH_O_DEF'		!SET HEADER
	INCLUDE 'MPH_T_DEF'
C
C  Parameters:
C
	INTEGER DBUFL			!LENGTH DATA BUFFER
	  PARAMETER (DBUFL=1024)
C
C  Arguments:
C
C
C  Function references:
C
	LOGICAL WNFRD			!READ DATA
	LOGICAL WNFWR			!WRITE DATA
C
C  Data declarations:
C
	INTEGER CVT			!CONVERSION TYPE
	INTEGER*2 DBH_T(0:1,0:1)	!DATA TRANSLATION
	  DATA DBH_T/4,0,0,1/
	BYTE GFH(0:GFHHDL-1)		!GENERAL FILE HEADER
	BYTE SGH(0:SGHHDL-1)		!SUB-GROUP HEADER
	  INTEGER SGHJ(0:SGHHDL/4-1)
	  EQUIVALENCE (SGH,SGHJ)
	BYTE MPH(0:MPHHDL-1)		!SET HEADER
	  INTEGER*2 MPHI(0:MPHHDL/2-1)
	  INTEGER MPHJ(0:MPHHDL/4-1)
	  EQUIVALENCE (MPH,MPHI,MPHJ)
	REAL DBUF(0:DBUFL-1)
C-
C
C INIT
C
C
C GENERAL FILE HEADER
C
	IF (.NOT.WNFRD(FCAOUT,GFHHDL,GFH,0)) THEN !READ GENERAL FILE HEADER
 10	  CONTINUE
	  CALL WNCTXT(F_TP,'!/I/O error on WMP file')
	  GOTO 900				!READY
	END IF
	IF (GFH(GFH_DATTP_B).EQ.0) GFH(GFH_DATTP_B)=1 !ASSUME VAX INPUT
	IF (GFH(GFH_DATTP_B).EQ.PRGDAT) THEN
	  CALL WNCTXT(F_TP,'!/Data already converted')
	  GOTO 800
	END IF
	CVT=GFH(GFH_DATTP_B)			!INPUT TYPE
	CALL WNTTTL(GFHHDL,GFH,GFH_T,CVT)	!CONVERT
	GFH(GFH_DATTP_B)=PRGDAT			!SET CURRENT DATA TYPE
	IF (.NOT.WNFWR(FCAOUT,GFHHDL,GFH,0)) GOTO 10 !REWRITE HEADER
C
C GROUP HEADERS
C
	J=1					!LEVEL 1
	J1=GFH_LINKG_1				!CURRENT GROUP
	J2=GFH_LINKG_1				!CURRENT LINK HEAD
 22	CONTINUE
	IF (.NOT.WNFRD(FCAOUT,SGHHDL,SGH,J1)) GOTO 10 !READ CURRENT
 20	CONTINUE
	IF (SGHJ(SGH_LINK_J).EQ.J2) THEN	!END OF LIST
	  J=J-1					!DECREASE LEVEL
	  IF (J.EQ.0) GOTO 21			!READY
	  J1=SGHJ(SGH_HEADH_J)-SGH_LINKG_1+SGH_LINK_1 !LOWER HEADER ADDR.
	  IF (.NOT.WNFRD(FCAOUT,SGHHDL,SGH,J1)) GOTO 10 !READ IT
	  J2=SGHJ(SGH_HEADH_J)			!NEW LINK HEAD
	  GOTO 20				!CONTINUE
	END IF
	J1=SGHJ(SGH_LINK_J)			!NEXT ENTRY
	IF (.NOT.WNFRD(FCAOUT,SGHHDL,SGH,J1)) GOTO 10 !READ IT
	CALL WNTTTL(SGHHDL,SGH,SGH_T,CVT)	!CONVERT IT
	IF (.NOT.WNFWR(FCAOUT,SGHHDL,SGH,J1)) GOTO 10 !WRITE IT
	IF (SGHJ(SGH_DATAP_J).EQ.0) THEN	!MORE LEVELS
	  IF (SGHJ(SGH_LINKG_J).EQ.J1+SGH_LINKG_1) GOTO 20 !NO NEXT LEVEL
	  J=J+1					!NEXT LEVEL
	  IF (J.GT.8) GOTO 10			!TOO MANY LEVELS
	  J2=J1+SGH_LINKG_1			!NEW HEADER PTR
	  J1=J2					!NEXT CURRENT
	  GOTO 22				!CONTINUE
	END IF
	GOTO 20					!MORE
 21	CONTINUE
C
C DO SETS
C
	IF (.NOT.WNFRD(FCAOUT,8,MPH,GFH_LINK_1)) GOTO 10 !READ SET HEADER START
30	CONTINUE
	J=MPHJ(MPH_LINK_J)			!NEXT IN LIST
	IF (J.EQ.GFH_LINK_1) GOTO 800		!ALL DONE
	IF (.NOT.WNFRD(FCAOUT,MPHHDL,MPH,J)) GOTO 10 !READ SET HEADER
	CALL WNTTTL(MPHHDL,MPH,MPH_T,CVT)	!CONVERT IT
	IF (.NOT.WNFWR(FCAOUT,MPHHDL,MPH,J)) GOTO 10 !WRITE SET HEADER
C
C MAPS
C
	IF (MPHI(MPH_DCD_I).EQ.2) THEN
	   DBH_T(0,0)=2				!I
	ELSE IF (MPHI(MPH_DCD_I).EQ.4) THEN
	   DBH_T(0,0)=3				!J
	ELSE IF (MPHI(MPH_DCD_I).EQ.5) THEN
	   DBH_T(0,0)=4				!E
	ELSE IF (MPHI(MPH_DCD_I).EQ.8) THEN
	   DBH_T(0,0)=5				!D
	ELSE 
	   DBH_T(0,0)=4				!ASSUME E
	END IF
C***	J=J+MPHHDL				!POINTER TO DATA
	J=MPHJ(MPH_MDP_J)			!POINTER TO DATA
	I2=MPHJ(MPH_NRA_J)*MPHJ(MPH_NDEC_J)	!MAP LENGTH
	DO WHILE (I2.GT.0)			!DO PER LINE
	  I3=MIN(I2,DBUFL)			!DO THIS TIME
	  I1=LB_E*I3				!IN BYTES
	  DBH_T(1,0)=I1				!TRANSLATION LENGTH
	  IF (.NOT.WNFRD(FCAOUT,I1,DBUF,J)) GOTO 10 !READ DATA
	  CALL WNTTTL(I1,DBUF,DBH_T,CVT)	!CONVERT
	  IF (.NOT.WNFWR(FCAOUT,I1,DBUF,J)) GOTO 10 !WRITE DATA
	  J=J+I1				!UPDATE POINTER
	  I2=I2-I3				!UPDATE COUNT
	END DO					!NEXT LINE
	GOTO 30					!NEXT SET
C
C READY
C
 800	CONTINUE
	CALL WNFCL(FCAOUT)			!CLOSE FILE
C
	RETURN
C
C ERROR
C
 900	CONTINUE
	CALL WNFCL(FCAOUT)			!CLOSE FILE
C
	RETURN					!READY
C
C
	END
